# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchcenterpincodemapping',
            name='dispatch_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_center_pincodes', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='dispatchcenterpincodemapping',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_center_mapping', to='addresses.Pincode'),
        ),
        migrations.AddField(
            model_name='dispatchcentercitymapping',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_center_mapping', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='dispatchcentercitymapping',
            name='dispatch_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_center_cities', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='addresses.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='addresses.State'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_area', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_address', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pincode_address', to='addresses.Pincode'),
        ),
        migrations.AddField(
            model_name='address',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_name_address_mapping', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_address', to='addresses.State'),
        ),
        migrations.AlterUniqueTogether(
            name='pincode',
            unique_together={('city', 'pincode')},
        ),
    ]
