# Generated by Django 2.1 on 2022-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='state_code_txt',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
