# Generated by Django 2.1 on 2018-10-26 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20181010_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_contact_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(code='INVALID_MOBILE_NUMBER', message='Mobile Number is not valid', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(code='INVALID_PINCODE', message='Invalid Pincode', regex='^[1-9][0-9]{5}$')]),
        ),
    ]
