# Generated by Django 2.1 on 2022-05-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_shopfcmtopic'),
        ('accounts', '0001_initial'),
        ('addresses', '0003_state_state_code_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city_routes', to='addresses.City')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses_route_created_by', to='accounts.User', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses_route_updated_by', to='accounts.User', verbose_name='Updated by')),
            ],
        ),
        migrations.CreateModel(
            name='ShopRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses_shoproute_created_by', to='accounts.User', verbose_name='Created by')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='route_shops', to='addresses.Route')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_routes', to='shops.Shop')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses_shoproute_updated_by', to='accounts.User', verbose_name='Updated by')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shoproute',
            unique_together={('shop', 'route')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('city', 'name')},
        ),
    ]
