# Generated by Django 2.1 on 2018-10-29 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20181029_1317'),
        ('addresses', '0006_auto_20181029_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='shop_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_name_address_mapping', to='shops.Shop'),
        ),
    ]
