# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailer_to_sp', '0002_auto_20220404_1624'),
        ('payments', '0002_shipmentdata_shipmentpaymentapproval_shipmentpaymentedit'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentpaymentstatus',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_payment_status', to='retailer_to_sp.Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_created_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='shipmentpayment',
            name='parent_order_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_order_payment', to='payments.OrderPayment'),
        ),
        migrations.AddField(
            model_name='shipmentpayment',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_payment', to='retailer_to_sp.OrderedProduct'),
        ),
        migrations.AddField(
            model_name='shipmentpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='paymentimage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_screenshot', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approver', to='accounts.UserWithName'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ManyToManyField(related_name='order_payment_data', through='payments.OrderPayment', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_user', to='accounts.UserWithName'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_screenshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.PaymentImage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_boy', to='accounts.UserWithName'),
        ),
        migrations.AddField(
            model_name='orderpaymentstatus',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment_status', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_created_by', to='accounts.UserWithName'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='parent_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_payment_order', to='payments.Payment'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_payment_updated_by', to='accounts.UserWithName'),
        ),
        migrations.CreateModel(
            name='PaymentApproval',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('payments.payment',),
        ),
        migrations.CreateModel(
            name='PaymentEdit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('payments.payment',),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentpayment',
            unique_together={('parent_order_payment', 'shipment')},
        ),
        migrations.AlterUniqueTogether(
            name='orderpayment',
            unique_together={('order', 'parent_payment')},
        ),
    ]
