# Generated by Django 2.1 on 2022-04-04 16:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkIncentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(null=True, upload_to='incentive/uploaded_file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('capping_applicable', models.BooleanField(default=False)),
                ('capping_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_of_calculation', models.DateField()),
                ('total_ex_tax_delivered_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('incentive', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncentiveDashboardDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('scheme_priority', models.SmallIntegerField(choices=[(0, 'P1'), (1, 'P2')])),
                ('purchase_value', models.FloatField(default=0)),
                ('incentive_earned', models.FloatField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Scheme name is not valid')])),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeShopMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('priority', models.SmallIntegerField(choices=[(0, 'P1'), (1, 'P2')])),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer_incentive.Scheme')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemeSlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('min_value', models.IntegerField(verbose_name='Slab Start Value')),
                ('max_value', models.IntegerField(verbose_name='Slab End Value')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_type', models.IntegerField(choices=[(0, 'Percentage'), (1, 'Value')], default=0)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer_incentive.Scheme')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
