# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('retailer_incentive', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeshopmapping',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='schemeshopmapping',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_mappings', to='accounts.User', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='accounts.User', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='incentivedashboarddetails',
            name='mapped_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer_incentive.Scheme'),
        ),
        migrations.AddField(
            model_name='incentivedashboarddetails',
            name='sales_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_details_sales_executive', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='incentivedashboarddetails',
            name='sales_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incentive_details_sales_manager', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='incentivedashboarddetails',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_incentive_incentive_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='incentive',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_incentive_incentive_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='bulkincentive',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incentive_uploaded_by', to='accounts.User'),
        ),
    ]
