# Generated by Django 2.1 on 2018-09-10 17:46

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid', regex='^[6-9]\\d{9}$')])),
                ('otp', models.CharField(max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('expires_in', models.IntegerField(default=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_otp', models.DateTimeField(default=django.utils.timezone.now)),
                ('resend_in', models.IntegerField(default=60)),
            ],
            options={
                'verbose_name': 'Phone OTP',
            },
        ),
    ]
