# Generated by Django 2.1 on 2018-09-05 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid', regex='^[6-9]\\d{9}$')]),
        ),
    ]
