# Generated by Django 2.1 on 2018-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='resend_in',
            field=models.IntegerField(default=30),
        ),
    ]
