# Generated by Django 2.1 on 2018-09-05 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20180905_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(editable=False, max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid', regex='^[6-9]\\d{9}$')]),
        ),
    ]
