# Generated by Django 2.1 on 2018-09-20 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20180911_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number is not valid', regex='^[6-9]\\d{9}$')]),
        ),
    ]
