# Generated by Django 2.1 on 2018-10-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_auto_20181010_1530'),
        ('otp', '0002_auto_20181009_1904'),
    ]

    operations = [
    ]
