# Generated by Django 2.1 on 2018-09-06 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_auto_20180905_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='is_valid',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='otp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid', regex='^[6-9]\\d{9}$')]),
        ),
    ]
