# Generated by Django 2.2 on 2022-06-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
