# Generated by Django 2.1 on 2018-09-28 13:38

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='active_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], default='1', verbose_name='Active Status'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.FileField(upload_to='', validators=[brand.models.validate_image]),
        ),
    ]
