# Generated by Django 2.1 on 2022-04-04 16:24

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('brand', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandposition',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='branddata',
            name='brand_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_position_data', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='branddata',
            name='slot',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_data', to='brand.BrandPosition'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'brand_parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_child', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='brand_updated_by', to='accounts.User'),
        ),
    ]
