# Generated by Django 2.1 on 2018-11-22 17:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brnd_parent', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_slug',
            field=models.SlugField(default=datetime.datetime(2018, 11, 22, 17, 26, 20, 967752), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name', 'brand_slug')},
        ),
    ]
