# Generated by Django 2.1 on 2018-11-23 10:58

import brand.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20181122_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_logo',
            field=models.FileField(null=True, upload_to='', validators=[brand.models.validate_image]),
        ),
    ]
