# Generated by Django 2.1 on 2018-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20181123_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(help_text='Please enter three character for SKU', max_length=3),
        ),
    ]
