# Generated by Django 2.1 on 2018-11-28 18:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_auto_20181128_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='INVALID_PINCODE', message='Invalid Pincode', regex='^[1-9][0-9]{5}$')]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_state_address', to='addresses.State'),
            preserve_default=False,
        ),
    ]
