# Generated by Django 2.1 on 2018-12-05 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20181128_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_code',
            field=models.CharField(help_text='Please enter three character for SKU', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]$', 'Only capital alphates allowed')]),
        ),
    ]
