# Generated by Django 2.1 on 2018-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_auto_20181205_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vendor_products_csv',
            field=models.FileField(blank=True, null=True, upload_to='vendor/vendor_products_csv'),
        ),
    ]
