# Generated by Django 2.1 on 2018-12-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_vendor_vendor_products_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_products_csv',
            field=models.FileField(upload_to='vendor/vendor_products_csv'),
        ),
    ]
