# Generated by Django 2.1 on 2018-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0011_auto_20181212_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_products_csv',
            field=models.FileField(blank=True, null=True, upload_to='vendor/vendor_products_csv'),
        ),
    ]
