version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
hooks:
  ApplicationStop:
    - location: stopapp.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: startapp.sh
      timeout: 300
      runas: root