version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project
hooks:
  ApplicationStop:
    - location: /home/ubuntu/project/stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /home/ubuntu/project/start.sh
      timeout: 300
      runas: root