version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/project/retailer-backend
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 350
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root