## This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.6.8-stretch

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          image: python:3.6.8-stretch
          deployment: production
          script:
            - echo "This script runs only on commit to the master branch."
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - cp -R . /tmp/retailer_backend
            - zip -r /tmp/artifact.zip appspec.yml scripts/*
            - python codedeploy_deploy.py

    staging:
      - step:
          name: Deploy
          image: python:3.6.8-stretch
          deployment: staging
          script:
            - echo "This script runs only on commit to the staging branch."
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - zip -r /tmp/artifact.zip appspec.yml scripts/*
            - python codedeploy_deploy.py

    dev:
      - step:
          name: Deploy
          image: python:3.6.8-stretch
          deployment: test
          script:
            - echo "This script runs only on commit to the staging branch."
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - zip -r /tmp/artifact.zip appspec.yml scripts/*
            - python codedeploy_deploy.py
    qa3:
      - step:
          name: Deploy
          image: python:3.6.8-stretch
          deployment: qa3
          script:
            - echo "This script runs only on commit to the staging branch."
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - zip -r /tmp/artifact.zip appspec.yml scripts/*
            - python codedeploy_deploy.py

