## This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          image: python:3.5.1
          script:
            - echo "This script runs only on commit to the master branch."
            - apt-get update
            - apt-get install -y zip
            - pip install boto3==1.3.0
            - cp -R . /tmp/ret_bck
            - zip -r /tmp/artifact.zip /tmp/ret_bck
            - python codedeploy_deploy.py

    dev:
      - step:
          name: Dev Deploy
          image: python:3.5.1
          script:
            - echo "This script runs only on commit to the dev branch."
