# Generated by Django 2.1 on 2022-04-04 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=255, null=True)),
                ('coupon_code', models.CharField(max_length=255, null=True)),
                ('limit_per_user_per_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('limit_of_usages', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('coupon_type', models.CharField(blank=True, choices=[('cart', 'cart'), ('catalog', 'catalog'), ('brand', 'brand'), ('category', 'category')], db_index=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('is_automate', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRuleSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rulename', models.CharField(max_length=255, null=True, unique=True)),
                ('rule_description', models.CharField(max_length=255, null=True)),
                ('all_users', models.BooleanField(default=False)),
                ('discount_qty_step', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('discount_qty_amount', models.FloatField(blank=True, default=0, null=True)),
                ('is_free_shipment', models.BooleanField(blank=True, default=False, null=True)),
                ('free_product_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('cart_qualifying_min_sku_value', models.FloatField(blank=True, default=0, null=True)),
                ('cart_qualifying_min_sku_item', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CusotmerCouponUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('brand', 'brand'), ('category', 'category'), ('b2c_category', 'b2c category')], max_length=255)),
                ('start_price', models.IntegerField()),
                ('end_price', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.FloatField(blank=True, default=0, null=True)),
                ('is_percentage', models.BooleanField(default=False)),
                ('max_discount', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetBrandMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSetProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_offer_name', models.CharField(max_length=255, null=True)),
                ('purchased_product_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('free_product_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('max_qty_per_use', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
