# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        ('products', '0001_initial'),
        ('categories', '0001_initial'),
        ('coupon', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulesetproductmapping',
            name='free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_product_coupon', to='products.Product'),
        ),
        migrations.AddField(
            model_name='rulesetproductmapping',
            name='purchased_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_product_coupon', to='products.Product'),
        ),
        migrations.AddField(
            model_name='rulesetproductmapping',
            name='retailer_free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_free_product_coupon', to='pos.RetailerProduct'),
        ),
        migrations.AddField(
            model_name='rulesetproductmapping',
            name='retailer_primary_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_purchased_product_coupon', to='pos.RetailerProduct'),
        ),
        migrations.AddField(
            model_name='rulesetproductmapping',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ruleset', to='coupon.CouponRuleSet'),
        ),
        migrations.AddField(
            model_name='rulesetbrandmapping',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_coupon', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='rulesetbrandmapping',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_ruleset', to='coupon.CouponRuleSet'),
        ),
        migrations.AddField(
            model_name='discount',
            name='b2c_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_category_discount', to='categories.B2cCategory'),
        ),
        migrations.AddField(
            model_name='discount',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Brand_discount', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='discount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_discount', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_discount_value', to='coupon.DiscountValue'),
        ),
    ]
