# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('coupon', '0002_auto_20220404_1624'),
        ('retailer_to_sp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusotmercouponusage',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon', to='retailer_to_sp.Cart'),
        ),
        migrations.AddField(
            model_name='cusotmercouponusage',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon', to='coupon.Coupon'),
        ),
        migrations.AddField(
            model_name='cusotmercouponusage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon_product', to='products.Product'),
        ),
    ]
