# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
        ('addresses', '0002_auto_20220404_1624'),
        ('pos', '0001_initial'),
        ('coupon', '0003_auto_20220404_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusotmercouponusage',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon_usage', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='couponruleset',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_value_id', to='coupon.DiscountValue'),
        ),
        migrations.AddField(
            model_name='couponruleset',
            name='free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_product', to='pos.RetailerProduct'),
        ),
        migrations.AddField(
            model_name='couponruleset',
            name='no_of_users_allowed',
            field=models.ManyToManyField(blank=True, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='couponlocation',
            name='buyer_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shop_coupon', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='couponlocation',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_shop_coupon', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='couponlocation',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_coupon', to='coupon.Coupon'),
        ),
        migrations.AddField(
            model_name='couponlocation',
            name='seller_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_shop_coupon', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_ruleset', to='coupon.CouponRuleSet'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_shop_coupon', to='shops.Shop'),
        ),
    ]
