# Generated by Django 2.2 on 2022-06-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20220404_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountvalue',
            name='is_point',
            field=models.BooleanField(default=False),
        ),
    ]
