# Generated by Django 2.2 on 2022-06-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_discountvalue_is_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_of_usages_per_customer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
