# Generated by Django 2.2 on 2022-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_coupon_limit_of_usages_per_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='limit_of_usages_per_customer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
