# Generated by Django 2.2 on 2022-06-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_auto_20220610_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_enable_on',
            field=models.CharField(blank=True, choices=[('pos', 'Pos'), ('online', 'Online'), ('all', 'All')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_shop_type',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('fofo', 'Fofo'), ('foco', 'Foco')], max_length=20, null=True),
        ),
    ]
