# Generated by Django 2.2 on 2022-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_auto_20220613_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_enable_on',
            field=models.CharField(blank=True, choices=[('pos', 'Pos'), ('online', 'Online'), ('all', 'All')], default='all', max_length=20),
        ),
    ]
