# Generated by Django 2.2 on 2022-06-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_auto_20220613_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponruleset',
            name='no_of_users_allowed',
            field=models.ManyToManyField(blank=True, to='accounts.User', verbose_name='Users Allowed'),
        ),
    ]
