# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_auto_20220617_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_enable_on',
            field=models.CharField(blank=True, choices=[('pos', 'Pos'), ('online', 'Online'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_shop_type',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('fofo', 'Fofo'), ('foco', 'Foco')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='limit_of_usages_per_customer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='discountvalue',
            name='is_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='couponruleset',
            name='no_of_users_allowed',
            field=models.ManyToManyField(blank=True, to='accounts.User', verbose_name='Users Allowed'),
        ),
    ]
