# Generated by Django 2.2 on 2022-06-22 12:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0018_auto_20220622_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True), size=8),
        ),
    ]
