# Generated by Django 2.2 on 2022-06-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0019_auto_20220622_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='froms',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='to',
        ),
    ]
