# Generated by Django 2.2 on 2022-06-22 15:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0021_auto_20220622_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_enable_on',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_shop_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='froms',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True), default=[], size=8),
        ),
    ]
