# Generated by Django 2.2 on 2022-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0022_auto_20220622_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_enable_on',
            field=models.CharField(blank=True, choices=[('pos', 'Pos'), ('online', 'Online'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_shop_type',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('fofo', 'Fofo'), ('foco', 'Foco'), ('superstore', 'SuperStore')], max_length=20, null=True),
        ),
    ]
