# Generated by Django 2.2 on 2022-06-22 16:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0023_auto_20220622_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True), default=[], size=8),
        ),
        migrations.AddField(
            model_name='coupon',
            name='froms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='to',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
