# Generated by Django 2.2 on 2022-06-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0025_rulesetproductmapping_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesetproductmapping',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
