# Generated by Django 2.2 on 2022-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0027_couponruleset_parent_free_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type_name',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=20, null=True),
        ),
    ]
