# Generated by Django 2.2 on 2022-07-06 15:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220617_1613'),
        ('coupon', '0029_auto_20220704_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True), default=[], size=8),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type_name',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='froms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='to',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='couponruleset',
            name='parent_free_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_free_product', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_enable_on',
            field=models.CharField(blank=True, choices=[('pos', 'Pos'), ('online', 'Online'), ('all', 'All'), ('superstore', 'SuperStore')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_shop_type',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('fofo', 'Fofo'), ('foco', 'Foco'), ('superstore', 'SuperStore')], max_length=20, null=True),
        ),
    ]
