# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topskuproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_sku_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='topskuproduct',
            name='top_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_top_sku', to='offer.TopSKU'),
        ),
        migrations.AddField(
            model_name='topsku',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='topsku',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
