# Generated by Django 2.1 on 2022-04-04 16:24

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
        ('brand', '0002_auto_20220404_1624'),
        ('products', '0001_initial'),
        ('categories', '0001_initial'),
        ('offer', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='topsku',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='topsku',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_sku_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='offerpage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_page_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='offer_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_banner_log', to='offer.OfferBanner'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='offer_banner_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_banner_slot_log', to='offer.OfferBannerSlot'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='offer_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_page_log', to='offer.OfferPage'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='top_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_sku_log', to='offer.TopSKU'),
        ),
        migrations.AddField(
            model_name='offerlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='offerbannerslot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='offerbannerslot',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.OfferPage'),
        ),
        migrations.AddField(
            model_name='offerbannerslot',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_banner_slot_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='offerbannerposition',
            name='offerbannerslot',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.OfferBannerSlot'),
        ),
        migrations.AddField(
            model_name='offerbannerposition',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.OfferPage'),
        ),
        migrations.AddField(
            model_name='offerbannerposition',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='offerbannerdata',
            name='offer_banner_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_banner_position_data', to='offer.OfferBanner'),
        ),
        migrations.AddField(
            model_name='offerbannerdata',
            name='slot',
            field=adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_ban_data', to='offer.OfferBannerPosition'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='brand',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='category',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Product'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='sub_brand',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_banner_subbrand', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='sub_category',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_banner_subcategory', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='offerbanner',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='offer_banner_updated_by', to='accounts.User'),
        ),
    ]
