# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        ('categories', '0001_initial'),
        ('cms', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_landing_pages', to='products.Product'),
        ),
        migrations.AddField(
            model_name='landingpageproducts',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_landingpageproducts_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_landing_pages', to='cms.Application'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_landingpage_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='page_function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_pages', to='cms.Functions'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_landingpage_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='functions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_functions_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='functions',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_functions_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='cardversion',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='cms.Card'),
        ),
        migrations.AddField(
            model_name='cardversion',
            name='card_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.CardData'),
        ),
        migrations.AddField(
            model_name='cardversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='cardversion',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_cardversion_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='card_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.CardData'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_carditem_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='subbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
        migrations.AddField(
            model_name='carditem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_carditem_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='carddata',
            name='card_function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='function_cards', to='cms.Functions'),
        ),
        migrations.AddField(
            model_name='carddata',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_carddata_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='carddata',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_carddata_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='card',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cms.Application'),
        ),
        migrations.AddField(
            model_name='card',
            name='brand_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_brand_subtype', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='card',
            name='category_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cms_cartegory_subtype', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_card_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_card_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='applicationpage',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='cms.Application'),
        ),
        migrations.AddField(
            model_name='applicationpage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_applicationpage_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='applicationpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_pages', to='cms.Page'),
        ),
        migrations.AddField(
            model_name='applicationpage',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_applicationpage_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='application',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cms_application_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
    ]
