# Generated by Django 2.1 on 2022-04-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('product', 'Product'), ('category', 'Category'), ('brand', 'Brand'), ('text', 'Text')], max_length=10),
        ),
    ]
