# Generated by Django 2.1 on 2022-04-17 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20220414_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_data_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Product'), (2, 'Category'), (3, 'Brand'), (4, 'Landing Page')], null=True),
        ),
        migrations.AddField(
            model_name='carditem',
            name='content_id',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
