# Generated by Django 2.1 on 2022-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20220418_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image_data_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Product'), (2, 'Category'), (3, 'Brand'), (4, 'Landing Page'), (5, 'B2C Category')], null=True),
        ),
    ]
