# Generated by Django 2.2 on 2022-07-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_templates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Templates',
        ),
    ]
