# Generated by Django 2.2 on 2022-07-06 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20220706_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='app',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='cms.Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/images'),
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
