# Generated by Django 2.2 on 2022-07-06 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_auto_20220706_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='app',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
    ]
