# Generated by Django 2.2 on 2022-07-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_auto_20220706_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='functions',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Functions_app', to='cms.Application'),
            preserve_default=False,
        ),
    ]
