# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
        ('franchise', '0001_initial'),
        ('wms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fbin',
            fields=[
            ],
            options={
                'verbose_name': 'Bin',
                'proxy': True,
                'indexes': [],
            },
            bases=('wms.bin',),
        ),
        migrations.AddField(
            model_name='wmsinventoryhistory',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='wmsinventoryhistory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='shoplocationmap',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop', unique=True, verbose_name='Shop Name'),
        ),
    ]
