from django.contrib.auth import get_user_model
from django.db import models

# Create your models here.
from categories.models import BaseTimeModel


class ZohoFileUpload(BaseTimeModel):
    file = models.FileField(upload_to='zoho/zoho_files/')
    upload_type = models.CharField(max_length=50, default='')
    updated_by = models.ForeignKey(
        get_user_model(), null=True, related_name='zoho_file_uploaded_by',
        on_delete=models.DO_NOTHING
    )

    def __str__(self):
        return f"BulkUpload for Zoho File Upload updated at {self.created_at} by {self.updated_by}"


class ZohoCreditNote(models.Model):

    credit_note_date = models.CharField(max_length=100, null=True, blank=True)
    product_id = models.CharField(max_length=100, null=True, blank=True)
    credit_notes_id = models.CharField(max_length=100, null=True, blank=True)
    credit_note_number = models.CharField(max_length=100, null=True, blank=True)
    credit_note_status = models.CharField(max_length=100, null=True, blank=True)
    customer_name = models.CharField(max_length=100, null=True, blank=True)
    billing_attention = models.CharField(max_length=100, null=True, blank=True)
    billing_address = models.CharField(max_length=100, null=True, blank=True)
    billing_street_2 = models.CharField(max_length=100, null=True, blank=True)
    billing_city = models.CharField(max_length=100, null=True, blank=True)
    billing_state = models.CharField(max_length=100, null=True, blank=True)
    billing_country = models.CharField(max_length=100, null=True, blank=True)
    billing_code = models.CharField(max_length=100, null=True, blank=True)
    billing_phone = models.CharField(max_length=100, null=True, blank=True)
    billing_fax = models.CharField(max_length=100, null=True, blank=True)
    shipping_attention = models.CharField(max_length=100, null=True, blank=True)
    shipping_address = models.CharField(max_length=100, null=True, blank=True)
    shipping_street_2 = models.CharField(max_length=100, null=True, blank=True)
    shipping_city = models.CharField(max_length=100, null=True, blank=True)
    shipping_state = models.CharField(max_length=100, null=True, blank=True)
    shipping_country = models.CharField(max_length=100, null=True, blank=True)
    shipping_phone = models.CharField(max_length=100, null=True, blank=True)
    shipping_code = models.CharField(max_length=100, null=True, blank=True)
    shipping_fax = models.CharField(max_length=100, null=True, blank=True)
    customer_id = models.CharField(max_length=100, null=True, blank=True)
    currency_code = models.CharField(max_length=100, null=True, blank=True)
    exchange_rate = models.CharField(max_length=100, null=True, blank=True)
    is_inclusive_tax = models.CharField(max_length=100, null=True, blank=True)
    total = models.CharField(max_length=100, null=True, blank=True)
    balance = models.CharField(max_length=100, null=True, blank=True)
    entity_discount_percent = models.CharField(max_length=100, null=True, blank=True)
    notes = models.CharField(max_length=100, null=True, blank=True)
    terms_conditions = models.CharField(max_length=100, null=True, blank=True)
    reference = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax_id = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax_amount = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax_name = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax_type = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_tax_exemption_code = models.CharField(max_length=100, null=True, blank=True)
    shipping_charge_sac_code = models.CharField(max_length=100, null=True, blank=True)
    adjustment = models.CharField(max_length=100, null=True, blank=True)
    branch_id = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_status = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_reference_number = models.CharField(max_length=100, null=True, blank=True)
    tcs_amount = models.CharField(max_length=100, null=True, blank=True)
    associated_invoice_number = models.CharField(max_length=100, null=True, blank=True)
    associated_invoice_date = models.CharField(max_length=100, null=True, blank=True)
    is_discount_before_tax = models.CharField(max_length=100, null=True, blank=True)
    item_name = models.CharField(max_length=100, null=True, blank=True)
    discount = models.CharField(max_length=100, null=True, blank=True)
    discount_amount = models.CharField(max_length=100, null=True, blank=True)
    quantity = models.CharField(max_length=100, null=True, blank=True)
    item_desc = models.CharField(max_length=100, null=True, blank=True)
    item_tax_amount = models.CharField(max_length=100, null=True, blank=True)
    item_total = models.CharField(max_length=100, null=True, blank=True)
    applied_invoice_number = models.CharField(max_length=100, null=True, blank=True)
    branch_name = models.CharField(max_length=100, null=True, blank=True)
    cgst_rate = models.CharField(max_length=100, null=True, blank=True)
    sgst_rate = models.CharField(max_length=100, null=True, blank=True)
    igst_rate = models.CharField(max_length=100, null=True, blank=True)
    cess_rate = models.CharField(max_length=100, null=True, blank=True)
    cgst_fcy = models.CharField(max_length=100, null=True, blank=True)
    sgst_fcy = models.CharField(max_length=100, null=True, blank=True)
    igst_fcy = models.CharField(max_length=100, null=True, blank=True)
    cess_fcy = models.CharField(max_length=100, null=True, blank=True)
    cgst = models.CharField(max_length=100, null=True, blank=True)
    sgst = models.CharField(max_length=100, null=True, blank=True)
    igst = models.CharField(max_length=100, null=True, blank=True)
    cess = models.CharField(max_length=100, null=True, blank=True)
    reason = models.CharField(max_length=100, null=True, blank=True)
    project_id = models.CharField(max_length=100, null=True, blank=True)
    project_name = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_qrjson = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_qr_raw_data = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_ack_number = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_ack_date = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_cancel_remark = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_cancel_reason = models.CharField(max_length=100, null=True, blank=True)
    e_invoice_failure_reason = models.CharField(max_length=100, null=True, blank=True)
    supplier_org_name = models.CharField(max_length=100, null=True, blank=True)
    supplier_gst_registration_number = models.CharField(max_length=100, null=True, blank=True)
    supplier_street_address = models.CharField(max_length=100, null=True, blank=True)
    supplier_city = models.CharField(max_length=100, null=True, blank=True)
    supplier_state = models.CharField(max_length=100, null=True, blank=True)
    supplier_country = models.CharField(max_length=100, null=True, blank=True)
    supplier_zipcode = models.CharField(max_length=100, null=True, blank=True)
    supplier_phone = models.CharField(max_length=100, null=True, blank=True)
    supplier_e_mail = models.CharField(max_length=100, null=True, blank=True)
    supply_type = models.CharField(max_length=100, null=True, blank=True)
    tax1_id = models.CharField(max_length=100, null=True, blank=True)
    item_tax = models.CharField(max_length=100, null=True, blank=True)
    item_tax = models.CharField(max_length=100, null=True, blank=True)
    item_tax_type = models.CharField(max_length=100, null=True, blank=True)
    reverse_charge_tax_name = models.CharField(max_length=100, null=True, blank=True)
    reverse_charge_tax_rate = models.CharField(max_length=100, null=True, blank=True)
    reverse_charge_tax_type = models.CharField(max_length=100, null=True, blank=True)
    place_of_supply_with_state_code = models.CharField(max_length=100, null=True, blank=True)
    gst_treatment = models.CharField(max_length=100, null=True, blank=True)
    gst_identification_number_gstin = models.CharField(max_length=100, null=True, blank=True)
    tcs_tax_name = models.CharField(max_length=100, null=True, blank=True)
    tcs_percentage = models.CharField(max_length=100, null=True, blank=True)
    nature_of_collection = models.CharField(max_length=100, null=True, blank=True)
    sales_person = models.CharField(max_length=100, null=True, blank=True)
    discount_type = models.CharField(max_length=100, null=True, blank=True)
    place_of_supply = models.CharField(max_length=100, null=True, blank=True)
    subtotal = models.CharField(max_length=100, null=True, blank=True)
    round_off = models.CharField(max_length=100, null=True, blank=True)
    adjustment_description = models.CharField(max_length=100, null=True, blank=True)
    subject = models.CharField(max_length=100, null=True, blank=True)
    reference_invoice_type = models.CharField(max_length=100, null=True, blank=True)
    item_type = models.CharField(max_length=100, null=True, blank=True)
    template_name = models.CharField(max_length=100, null=True, blank=True)
    usage_unit = models.CharField(max_length=100, null=True, blank=True)
    item_price = models.CharField(max_length=100, null=True, blank=True)
    hsn_sac = models.CharField(max_length=100, null=True, blank=True)
    account = models.CharField(max_length=100, null=True, blank=True)
    account_code = models.CharField(max_length=100, null=True, blank=True)
    item_tax_exemption_reason = models.CharField(max_length=100, null=True, blank=True)
    entity_discount_amount = models.CharField(max_length=100, null=True, blank=True)



# class ZohoInvoice(models.Model):
#     pass


# class ZohoCustomers(models.Model):
#     pass

