# Generated by Django 2.1 on 2022-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoinvoice',
            name='e_invoice_pdf_generated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
