# Generated by Django 2.1 on 2022-04-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20220414_1706'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardlog',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
    ]
