# Generated by Django 2.1 on 2022-04-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_rewardlog_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralcode',
            options={'permissions': (('has_gf_employee_permission', 'Has GF Employee Permission'),), 'verbose_name': '   User'},
        ),
        migrations.AddField(
            model_name='referral',
            name='referee_reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referral',
            name='user_linked_type',
            field=models.CharField(blank=True, choices=[('DIGITAL_MARKETING', 'Digital Marketing'), ('MARKETING', 'Marketing'), ('FIELD_EXECUTIVE', 'Field Executive'), ('SHOP_OWNERS', 'Shop Owners'), ('PEPPER_TAP_CUSTOMER', 'PepperTap Customer')], max_length=20, null=True),
        ),
    ]
