# Generated by Django 2.2 on 2022-06-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_userwishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='gf_prod_id',
        ),
        migrations.RemoveField(
            model_name='userwishlist',
            name='retail_prod_id',
        ),
        migrations.RemoveField(
            model_name='userwishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
        migrations.DeleteModel(
            name='UserWishlist',
        ),
    ]
