# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('ecom', '0001_initial'),
        ('retailer_to_sp', '0001_initial'),
        ('pos', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomCart',
            fields=[
            ],
            options={
                'verbose_name': 'Ecommerce - Cart',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.cart',),
        ),
        migrations.CreateModel(
            name='EcomCartProductMapping',
            fields=[
            ],
            options={
                'verbose_name': 'Ecommerce - Cart Product Mapping',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.cartproductmapping',),
        ),
        migrations.CreateModel(
            name='EcomOrderedProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Ecommerce - Ordered Product',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.orderedproduct',),
        ),
        migrations.CreateModel(
            name='EcomOrderedProductMapping',
            fields=[
            ],
            options={
                'verbose_name': 'Ecommerce - Ordered Product Mapping',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.orderedproductmapping',),
        ),
        migrations.CreateModel(
            name='EcomTrip',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('pos.postrip',),
        ),
        migrations.AddField(
            model_name='tagproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag_ecom', to='pos.RetailerProduct'),
        ),
        migrations.AddField(
            model_name='tagproductmapping',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_ecom', to='ecom.Tag'),
        ),
        migrations.AddField(
            model_name='ecomorderaddress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_address_order', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='ecomorderaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecom_address_order', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='ecomorderaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_address_order', to='addresses.State'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_address_ecom', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_address_ecom', to='addresses.State'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecom_user_address', to='accounts.User'),
        ),
    ]
