# Generated by Django 2.1 on 2022-04-18 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_auto_20220417_2010'),
        ('accounts', '0001_initial'),
        ('shops', '0006_auto_20220414_1706'),
        ('ecom', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPastPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_purchased_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold', to='pos.RetailerProduct')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold', to='shops.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_purchases', to='accounts.User')),
            ],
        ),
    ]
