# Generated by Django 2.1 on 2022-04-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20220420_1250'),
        ('accounts', '0001_initial'),
        ('ecom', '0003_userpastpurchases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserLocationMappedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_location', to='shops.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_location', to='accounts.User')),
            ],
            options={
                'permissions': (('can_have_shop_user_mapping_view_permission', 'Can View shop & user mapping Log'),),
            },
        ),
    ]
