# Generated by Django 2.2 on 2022-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_shopuserlocationmappedlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='extra_information',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
