# Generated by Django 2.2 on 2022-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
