# Generated by Django 2.2 on 2022-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20220727_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
