# Generated by Django 2.2 on 2022-08-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_languages_is_publish'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.RemoveField(
            model_name='address',
            name='extra_information',
        ),
    ]
