# Generated by Django 2.2 on 2022-08-03 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_parentproduct_is_kvi'),
        ('ecom', '0009_auto_20220802_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpastpurchases',
            name='retail_Product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retail_products_sold', to='products.Product'),
        ),
    ]
