# Generated by Django 2.2 on 2022-08-03 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_userpastpurchases_retail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpastpurchases',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold', to='pos.RetailerProduct'),
        ),
    ]
