# Generated by Django 2.2 on 2022-08-03 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20220617_1613'),
        ('ecom', '0011_auto_20220803_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpastpurchases',
            name='buyer_shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold_to', to='shops.Shop'),
        ),
        migrations.AlterField(
            model_name='userpastpurchases',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold', to='shops.Shop'),
        ),
    ]
