# Generated by Django 2.2 on 2022-08-03 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20220803_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpastpurchases',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products_sold', to='shops.Shop'),
        ),
        migrations.AlterField(
            model_name='userpastpurchases',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_purchases', to='accounts.User'),
        ),
    ]
