# Generated by Django 2.2 on 2022-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220602_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronrunlog',
            name='cron_name',
            field=models.CharField(choices=[('PICKUP_CREATION_CRON', 'Picklist Generation Cron'), ('AUDIT_PICKUP_REFRESH_CRON', 'Refresh Picklist After Audit Cron'), ('FRANCHISE_SALES_RETURNS_CRON', 'Adjust Sales/Returns Franchise Inventory Cron'), ('HDPOS_USERS_FETCH_CRON', 'Fetch Registered Customers on Hdpos'), ('MARKETING_REWARDS_NOTIFY', 'Notify users about rewards'), ('AUTO_ORDER_PROCESSING_CRON', 'Auto Order Processing'), ('SCHEME_EXPIRY_CRON', 'Deactivate expired schemes and mappings'), ('ARS_CRON', 'ARS Cron'), ('PO_CREATION_CRON', 'PO creation Cron')], max_length=50),
        ),
    ]
