# Generated by Django 2.1 on 2018-10-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_document_type', models.CharField(choices=[('pc', 'PAN Card'), ('dl', 'Driving License'), ('uidai', 'Aadhaar Card')], default='uidai', max_length=100)),
                ('user_document_number', models.CharField(max_length=100)),
                ('user_document_photo', models.FileField(upload_to='user_photos/documents/')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_photo',
            field=models.FileField(blank=True, null=True, upload_to='user_photos/'),
        ),
        migrations.AddField(
            model_name='userdocument',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to='accounts.User'),
        ),
    ]
