# Generated by Django 2.1 on 2018-09-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User')),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('attempts', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
