# Generated by Django 2.1 on 2018-09-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
