# Generated by Django 2.2 on 2022-08-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_app_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='app_language',
        ),
    ]
