# Generated by Django 2.1 on 2018-09-19 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180919_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid', regex='^[6-9]\\d{9}$')]),
        ),
    ]
