# Generated by Django 2.1 on 2018-09-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180903_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_in',
            field=models.IntegerField(default=5),
        ),
    ]
