# Generated by Django 2.1 on 2018-09-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180903_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
