# Generated by Django 2.1 on 2018-10-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0003_auto_20181017_1147'),
        ('products', '0009_productpricecsv_area'),
        ('addresses', '0003_auto_20181010_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_status', models.CharField(blank=True, choices=[('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_last_modified_user_cart', to='accounts.User')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_shop_cart', to='shops.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_cart_list', to='retailer_to_sp.Cart')),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_cart_product_mapping', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mrp', models.FloatField(default=0)),
                ('total_discount_amount', models.FloatField(default=0)),
                ('total_tax_amount', models.FloatField(default=0)),
                ('total_final_amount', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_billing_address_order', to='addresses.Address')),
                ('buyer_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_buyer_shop_order', to='shops.Shop')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_modified_user', to='accounts.User')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_ordered_by_user', to='accounts.User')),
                ('ordered_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_cart_mapping', to='retailer_to_sp.Cart')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_received_by_user', to='accounts.User')),
                ('seller_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_seller_shop_order', to='shops.Shop')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_shipping_address_order', to='addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_last_modified_user_order', to='accounts.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_order_product', to='retailer_to_sp.Order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_ordered_product_received_by_user', to='accounts.User')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_shipped_product_ordered_by_user', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_qty', models.PositiveIntegerField(default=0)),
                ('delivered_qty', models.PositiveIntegerField(default=0)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_last_modified_user_order_product', to='accounts.User')),
                ('ordered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_product_order_product_mapping', to='retailer_to_sp.OrderedProduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_product_order_product', to='products.Product')),
            ],
        ),
    ]
