# Generated by Django 2.1 on 2018-10-23 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20181017_1147'),
        ('retailer_to_sp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_user_cart', to='shops.Shop'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
