# Generated by Django 2.1 on 2022-04-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceData',
            fields=[
            ],
            options={
                'verbose_name': 'e-invoice',
                'verbose_name_plural': 'e-invoices',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.invoice',),
        ),
        migrations.CreateModel(
            name='ENoteData',
            fields=[
            ],
            options={
                'verbose_name': 'e-note',
                'verbose_name_plural': 'e-notes',
                'proxy': True,
                'indexes': [],
            },
            bases=('retailer_to_sp.note',),
        ),
    ]
