# Generated by Django 2.1 on 2018-10-25 18:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('retailer_to_sp', '0003_auto_20181023_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 25, 18, 48, 27, 339145)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproductmapping',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartproductmapping',
            name='qty_error_msg',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_user_order', to='accounts.User'),
        ),
    ]
