# Generated by Django 2.1 on 2018-10-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0004_auto_20181025_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
