# Generated by Django 2.1 on 2022-05-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0005_cart_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='category',
        ),
    ]
