# Generated by Django 2.1 on 2018-11-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181029_1442'),
        ('retailer_to_sp', '0006_remove_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_last_modified_user_note', to='accounts.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_note', to='retailer_to_sp.Order')),
                ('ordered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_product_note', to='retailer_to_sp.OrderedProduct')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('cash_in_delivery', 'Cash In Delivery'), ('neft', 'NEFT')], max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(default=0)),
                ('payment_status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='done', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_retailer_payment', to='retailer_to_sp.Order')),
            ],
        ),
    ]
