# Generated by Django 2.1 on 2022-05-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0006_remove_cart_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmapping',
            name='product_mrp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
