# Generated by Django 2.1 on 2022-05-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0007_cartproductmapping_product_mrp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproductmapping',
            name='product_mrp',
        ),
    ]
