# Generated by Django 2.1 on 2018-11-01 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0007_note_retailerpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerpayment',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash_in_delivery', 'Cash In Delivery'), ('neft', 'NEFT')], default=datetime.datetime(2018, 11, 1, 11, 30, 7, 253455), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='reference_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='RetailerPayment',
        ),
    ]
