# Generated by Django 2.1 on 2022-05-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0008_remove_cartproductmapping_product_mrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='redeem_factor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
