# Generated by Django 2.1 on 2018-11-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0009_auto_20181101_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('pending', 'Pending')], max_length=255, null=True),
        ),
    ]
