# Generated by Django 2.2 on 2022-06-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('retailer_to_sp', '0011_auto_20220518_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_order', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_deliveries', to='accounts.UserWithName', verbose_name='Delivery Boy'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('BULK', 'Bulk'), ('DISCOUNTED', 'Discounted'), ('BASIC', 'Basic'), ('EC0M', 'Ecom'), ('SUPERSTORE', 'Super Store'), ('SUPERSTORE_RETAIL', 'Super Store Retail')], default='RETAIL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_app_type',
            field=models.CharField(blank=True, choices=[('pos_walkin', 'Pos Walkin'), ('pos_ecomm', 'Pos Ecomm'), ('pos_superstore', 'Pos Super Store')], max_length=50, null=True),
        ),
    ]
