# Generated by Django 2.2 on 2022-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0012_auto_20220602_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='shipment_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='supermart/shipment/label/documents/'),
        ),
    ]
