# Generated by Django 2.1 on 2018-11-27 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0012_customercare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=4, default='0.0000', max_digits=20)),
                ('payment_choice', models.CharField(choices=[('cash_in_delivery', 'Cash In Delivery'), ('neft', 'NEFT')], max_length=30, null=True)),
                ('neft_reference_number', models.CharField(max_length=20, null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_payment', to='retailer_to_sp.Order')),
            ],
        ),
    ]
