# Generated by Django 2.1 on 2018-12-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered', 'Ordered'), ('order_shipped', 'Order Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered', 'Ordered'), ('order_shipped', 'Order Shipped'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
