# Generated by Django 2.2 on 2022-06-08 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0013_orderedproduct_shipment_label_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='shipment_label_pdf',
        ),
    ]
