# Generated by Django 2.2 on 2022-06-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0014_remove_orderedproduct_shipment_label_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='shipment_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='supermart/shipment/label/documents/'),
        ),
    ]
