# Generated by Django 2.1 on 2018-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0014_auto_20181201_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('neft', 'NEFT')], max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_choice',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('neft', 'NEFT')], max_length=30, null=True),
        ),
    ]
