# Generated by Django 2.2 on 2022-06-17 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0016_auto_20220613_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='points_added',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='ref_return_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_return_orders', to='retailer_to_sp.ReturnOrder'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='return_type',
            field=models.CharField(choices=[('RETAILER', 'Retailer returns'), ('SUPERSTORE', 'Superstore returns'), ('SUPERSTORE_WAREHOUSE', 'Superstore warehouse returns')], default='SUPERSTORE', max_length=50, verbose_name='Type for returns'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_status',
            field=models.CharField(blank=True, choices=[('RETURN_REQUESTED', 'Return requested'), ('RETURN_INITIATED', 'Return initiated'), ('CUSTOMER_ITEM_PICKED', 'Customer item picked'), ('STORE_ITEM_PICKED', 'Retailer Item Picked'), ('DC_DROPPED', 'DC Dropped'), ('WH_DROPPED', 'WH Dropped'), ('RETURN_CANCEL', 'Return cancelled'), ('RETURN_COMPLETE', 'Return completed')], max_length=50, null=True, verbose_name='Status for Return'),
        ),
    ]
