# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20220617_1613'),
        ('pos', '0037_auto_20220617_1613'),
        ('accounts', '0001_initial'),
        ('products', '0011_auto_20220617_1613'),
        ('retailer_to_sp', '0018_auto_20220617_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=255, null=True)),
                ('return_type', models.CharField(choices=[('RETAILER', 'Retailer returns'), ('SUPERSTORE', 'Superstore returns'), ('SUPERSTORE_WAREHOUSE', 'Superstore warehouse returns')], default='SUPERSTORE', max_length=50, verbose_name='Type for returns')),
                ('return_status', models.CharField(blank=True, choices=[('RETURN_REQUESTED', 'Return requested'), ('RETURN_INITIATED', 'Return initiated'), ('CUSTOMER_ITEM_PICKED', 'Customer item picked'), ('STORE_ITEM_PICKED', 'Retailer Item Picked'), ('DC_DROPPED', 'DC Dropped'), ('WH_DROPPED', 'WH Dropped'), ('RETURN_CANCEL', 'Return cancelled'), ('RETURN_COMPLETE', 'Return completed')], max_length=50, null=True, verbose_name='Status for Return')),
                ('return_reason', models.CharField(blank=True, choices=[('defective_damaged_item', 'Defective / Damaged item'), ('wrong_item_delivered', 'Wrong item delivered'), ('item_did_not_match_description', 'Item did not match description'), ('other', 'other reason')], max_length=50, null=True, verbose_name='Reason for Return')),
                ('return_pickup_method', models.CharField(blank=True, choices=[('DROP_AT_STORE', 'Drop at Store'), ('HOME_PICKUP', 'Home Pickup')], max_length=50, null=True, verbose_name='Method for Product pick up')),
                ('other_return_reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verbose return reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_return_orders', to='accounts.User')),
                ('buyer_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_shop_return_orders', to='shops.Shop')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified_return_order', to='accounts.User')),
                ('ref_return_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_return_orders', to='retailer_to_sp.ReturnOrder')),
                ('return_item_pickup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_item_pickups', to='accounts.UserWithName', verbose_name='Return Item Pick up')),
                ('seller_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_shop_return_orders', to='shops.Shop')),
            ],
            options={
                'verbose_name': 'Return Order request',
                'verbose_name_plural': 'Return Order requests',
            },
        ),
        migrations.CreateModel(
            name='ReturnOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_qty', models.PositiveIntegerField(default=0, verbose_name='Returned Quantity')),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_by_return_orders', to='accounts.User')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_order_products', to='products.Product')),
                ('retailer_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_order_retailer_products', to='pos.RetailerProduct')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_order_products', to='retailer_to_sp.ReturnOrder')),
            ],
            options={
                'verbose_name': 'Return Order Product',
                'verbose_name_plural': 'Return Order Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True, verbose_name='Latitude For Ecommerce order'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True, verbose_name='Longitude For Ecommerce order'),
        ),
        migrations.AddField(
            model_name='order',
            name='reference_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_order', to='retailer_to_sp.Order'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='delivery_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipment_deliveries', to='accounts.UserWithName', verbose_name='Delivery Boy'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='points_added',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='shipment_label_pdf',
            field=models.FileField(blank=True, null=True, upload_to='supermart/shipment/label/documents/'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('BULK', 'Bulk'), ('DISCOUNTED', 'Discounted'), ('BASIC', 'Basic'), ('EC0M', 'Ecom'), ('SUPERSTORE', 'Super Store'), ('SUPERSTORE_RETAIL', 'Super Store Retail')], default='RETAIL', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_app_type',
            field=models.CharField(blank=True, choices=[('pos_walkin', 'Pos Walkin'), ('pos_ecomm', 'Pos Ecomm'), ('pos_superstore', 'Pos Super Store')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReturnOrderProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_image', models.FileField(upload_to='return_photos/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('return_order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_order_product_images', to='retailer_to_sp.ReturnOrderProduct')),
            ],
            options={
                'verbose_name': 'Return Order Product Image',
                'verbose_name_plural': 'Return Order Product Images',
            },
        ),
        migrations.AddField(
            model_name='returnorder',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_return_orders', to='retailer_to_sp.OrderedProduct'),
        ),
    ]
