# Generated by Django 2.2 on 2022-07-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0019_auto_20220617_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='points_added',
        ),
        migrations.AddField(
            model_name='pickerdashboard',
            name='is_clickable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='return_challan_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(db_index=True, max_length=255, unique=True)),
                ('invoice_sub_total', models.FloatField()),
                ('invoice_total', models.FloatField()),
                ('invoice_pdf', models.FileField(blank=True, null=True, upload_to='shop_photos/shop_name/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('return_order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_invoice', to='retailer_to_sp.ReturnOrder')),
            ],
            options={
                'verbose_name': 'Return Challan',
                'verbose_name_plural': 'Return Challans',
            },
        ),
    ]
