# Generated by Django 2.2 on 2022-07-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20220617_1613'),
        ('accounts', '0001_initial'),
        ('retailer_to_sp', '0020_auto_20220704_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='points_added',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='dc_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dc_location_return_orders', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='returnorder',
            name='reject_reason',
            field=models.CharField(blank=True, choices=[('USED_PRODUCT', 'Product is used'), ('DAMAGED_PRODUCT', 'Product is damaged'), ('PRODUCT_IMAGE_DIFF', 'Product does not matches with the images uploaded by the customer'), ('RETAILER_DENIED', 'Retailer Denied'), ('RETAILER_UNAVAILABLE', 'Retailer Not available')], max_length=50, null=True, verbose_name='Reason for Rejection'),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='damaged_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Damaged Quantity'),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='delivery_picked_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Picked Quantity'),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='expired_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Expired Quantity'),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='is_bck_return_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='is_return_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='return_shipment_barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='returnorderproduct',
            name='verified_return_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Verified Return Quantity'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('defective_damaged_item', 'Defective / Damaged item'), ('wrong_item_delivered', 'Wrong item delivered'), ('item_did_not_match_description', 'Item did not match description'), ('OTHER', 'other reason')], max_length=50, null=True, verbose_name='Reason for Return'),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='return_status',
            field=models.CharField(blank=True, choices=[('RETURN_REQUESTED', 'Return requested'), ('RETURN_INITIATED', 'Return initiated'), ('CUSTOMER_ITEM_PICKED', 'Customer item picked'), ('STORE_ITEM_PICKED', 'Retailer Item Picked'), ('DC_DROPPED', 'DC Dropped'), ('DC_ACCEPTED', 'DC accepted'), ('WH_DROPPED', 'WH Dropped'), ('WH_ACCEPTED', 'WH accepted'), ('RETURN_CANCEL', 'Return cancelled'), ('RETURN_COMPLETE', 'Return completed'), ('RETURN_REJECTED', 'Return Rejected')], max_length=50, null=True, verbose_name='Status for Return'),
        ),
        migrations.CreateModel(
            name='ReturnProductBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('return_qty', models.PositiveIntegerField(default=0)),
                ('expired_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('return_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_product_batches', to='retailer_to_sp.ReturnOrderProduct')),
            ],
        ),
        migrations.CreateModel(
            name='LastMileTripReturnMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('shipment_status', models.CharField(choices=[('TO_BE_LOADED', 'To be Loaded For Dispatch'), ('LOADING_FOR_DC', 'Loading For Dispatch'), ('LOADED_FOR_DC', 'Loaded For Dispatch'), ('CANCELLED', 'Cancelled')], max_length=100)),
                ('shipment_health', models.CharField(blank=True, choices=[('OKAY', 'Okay'), ('PARTIALLY_MISSING_DAMAGED', 'Partially Missing & Damaged'), ('PARTIALLY_DAMAGED', 'Partially Damaged'), ('PARTIALLY_MISSING', 'Partially Missing'), ('FULLY_DAMAGED', 'Fully Damaged'), ('FULLY_MISSING', 'Fully Missing')], max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_to_sp_lastmiletripreturnmapping_created_by', to='accounts.User', verbose_name='Created by')),
                ('loaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_mile_trip_returns_loaded', to='accounts.User')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_mile_trip_returns', to='retailer_to_sp.ReturnOrder')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_mile_trip_returns_details', to='retailer_to_sp.Trip')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_to_sp_lastmiletripreturnmapping_updated_by', to='accounts.User', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DispatchTripReturnOrderMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('return_order_status', models.CharField(choices=[('LOADED', 'Loaded'), ('UNLOADED', 'Unloaded'), ('DAMAGED_AT_LOADING', 'Damaged At Loading'), ('DAMAGED_AT_UNLOADING', 'Damaged At Unloading'), ('MISSING_AT_LOADING', 'Missing At Loading'), ('MISSING_AT_UNLOADING', 'Missing At Unloading'), ('CANCELLED', 'Cancelled'), ('PARTIALLY_VERIFIED', 'Partially Verified'), ('VERIFIED', 'Verified')], max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_to_sp_dispatchtripreturnordermapping_created_by', to='accounts.User', verbose_name='Created by')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trip_return_order', to='retailer_to_sp.ReturnOrder')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_order_details', to='retailer_to_sp.DispatchTrip')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='retailer_to_sp_dispatchtripreturnordermapping_updated_by', to='accounts.User', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarcodeGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(choices=[(6, 'Return Pickup')], max_length=15)),
                ('batch_size', models.PositiveSmallIntegerField(default=1)),
                ('last_sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_no', models.CharField(max_length=13)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='retailer_to_sp.BarcodeGenerator')),
            ],
        ),
    ]
