# Generated by Django 2.2 on 2022-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0022_auto_20220727_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoffers',
            name='coupon_type',
            field=models.CharField(choices=[('CATALOG', 'catalog'), ('BRAND', 'brand'), ('CART', 'cart'), ('NONE', 'none')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartoffers',
            name='sub_type',
            field=models.CharField(choices=[('NONE', 'none'), ('NO_OFFER', 'no offer'), ('DISCOUNT_ON_BRAND', 'discount_on_brand'), ('DISCOUNT_ON_CART', 'discount_on_cart'), ('DISCOUNT_ON_PRODUCT', 'discount_on_product')], max_length=20),
        ),
    ]
