# Generated by Django 2.2 on 2022-07-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0006_auto_20220617_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='putawaybininventory',
            name='inventory_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.InventoryType'),
        ),
        migrations.AlterField(
            model_name='warehouseinternalinventorychange',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('warehouse_adjustment', 'WareHouse Adjustment'), ('reserved', 'Reserved'), ('ordered', 'Ordered'), ('released', 'Released'), ('canceled', 'Canceled'), ('order_cancelled', 'Order Cancelled'), ('audit_adjustment', 'Audit Adjustment'), ('put_away_type', 'Put Away'), ('pickup_created', 'Pickup Created'), ('picked', 'Picked'), ('picking_cancelled', 'Picking Cancelled'), ('pickup_complete', 'Pickup Complete'), ('shipped_out', 'Shipped Out'), ('stock_correction_in_type', 'stock_correction_in_type'), ('stock_correction_out_type', 'stock_correction_out_type'), ('reschedule', 'Reschedule'), ('not_attempt', 'not_attempt'), ('expired', 'Expired'), ('repackaging', 'Repackaging'), ('manual_audit_add', 'Manual Audit Add'), ('manual_audit_deduct', 'Manual Audit Deduct'), ('audit_correction_add', 'Audit Correction Add'), ('audit_correction_deduct', 'Audit Correction Deduct'), ('franchise_batch_in', 'Franchise Batch In'), ('franchise_sales', 'Franchise Sales'), ('franchise_returns', 'Franchise Returns'), ('moved_to_discounted', 'Moved To Discounted'), ('added_as_discounted', 'Added As Discounted'), ('bin_marked_as_live', 'Bin marked as live'), ('bin_marked_as_not_live', 'Bin marked as not live')], max_length=25, null=True),
        ),
    ]
