# Generated by Django 2.2 on 2022-08-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0007_auto_20220727_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='putawaybininventory',
            name='inventory_type',
        ),
        migrations.AlterField(
            model_name='warehouseinternalinventorychange',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('warehouse_adjustment', 'WareHouse Adjustment'), ('reserved', 'Reserved'), ('ordered', 'Ordered'), ('released', 'Released'), ('canceled', 'Canceled'), ('order_cancelled', 'Order Cancelled'), ('audit_adjustment', 'Audit Adjustment'), ('put_away_type', 'Put Away'), ('pickup_created', 'Pickup Created'), ('picked', 'Picked'), ('picking_cancelled', 'Picking Cancelled'), ('pickup_complete', 'Pickup Complete'), ('shipped_out', 'Shipped Out'), ('stock_correction_in_type', 'stock_correction_in_type'), ('stock_correction_out_type', 'stock_correction_out_type'), ('reschedule', 'Reschedule'), ('not_attempt', 'not_attempt'), ('expired', 'Expired'), ('repackaging', 'Repackaging'), ('manual_audit_add', 'Manual Audit Add'), ('manual_audit_deduct', 'Manual Audit Deduct'), ('audit_correction_add', 'Audit Correction Add'), ('audit_correction_deduct', 'Audit Correction Deduct'), ('franchise_batch_in', 'Franchise Batch In'), ('franchise_sales', 'Franchise Sales'), ('franchise_returns', 'Franchise Returns'), ('moved_to_discounted', 'Moved To Discounted'), ('added_as_discounted', 'Added As Discounted')], max_length=25, null=True),
        ),
    ]
