# Generated by Django 2.1 on 2018-10-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('shops', '0002_auto_20181008_1319'),
        ('products', '0002_auto_20181008_1319'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOrderShipmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_status', models.CharField(choices=[('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_order', to='brand.Brand')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to='shops.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.PositiveIntegerField(default=0)),
                ('cart_price', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_list', to='gram_to_brand.Cart')),
                ('cart_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_mapping', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mrp', models.FloatField(default=0)),
                ('total_discount_amount', models.FloatField(default=0)),
                ('total_tax_amount', models.FloatField(default=0)),
                ('total_final_amount', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('ordered_to_brand', 'Ordered To Brand'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_order_modified_user', to='accounts.User')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_order_by_user', to='accounts.User')),
                ('ordered_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart_mapping', to='gram_to_brand.Cart')),
                ('ordered_shipment', models.ManyToManyField(related_name='order_shipment_mapping', to='gram_to_brand.CarOrderShipmentMapping')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_received_by_user', to='accounts.User')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_order', to='shops.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_qty', models.PositiveIntegerField(default=0)),
                ('changed_price', models.FloatField(default=0)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('car_order_shipment_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_order_shipment_mapping_shipment', to='gram_to_brand.CarOrderShipmentMapping')),
                ('cart_product_ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_mapping_shipment', to='gram_to_brand.CartProductMapping')),
            ],
        ),
    ]
