# Generated by Django 2.1 on 2018-10-14 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carordershipmentmapping',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_order_shipment', to='gram_to_brand.Cart'),
        ),
    ]
