# Generated by Django 2.1 on 2022-04-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gram_to_brand', '0002_auto_20220404_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProductMappingTaxLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('existing_gst', models.IntegerField(blank=True, choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], null=True)),
                ('existing_cess', models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True)),
                ('new_gst', models.IntegerField(blank=True, choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], null=True)),
                ('new_cess', models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cartproductmapping',
            name='cess',
            field=models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True),
        ),
        migrations.AddField(
            model_name='cartproductmapping',
            name='gst',
            field=models.IntegerField(blank=True, choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], null=True),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='discount_charges',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='insurance_charges',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='other_charges',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='total_freight_charges',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='total_grn_amount',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='cess_percentage',
            field=models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='product_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='product_invoice_gst',
            field=models.IntegerField(choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='cartproductmappingtaxlog',
            name='cart_product_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_product_mapping_tax_log', to='gram_to_brand.CartProductMapping'),
        ),
        migrations.AddField(
            model_name='cartproductmappingtaxlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gram_to_brand_cartproductmappingtaxlog_created_by', to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='cartproductmappingtaxlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gram_to_brand_cartproductmappingtaxlog_updated_by', to='accounts.User', verbose_name='Updated by'),
        ),
    ]
