# Generated by Django 2.2 on 2022-06-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0003_auto_20220406_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='po_type',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=50, null=True),
        ),
    ]
