# Generated by Django 2.1 on 2018-10-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181008_1319'),
        ('gram_to_brand', '0003_auto_20181015_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproductmapping',
            old_name='cart_products',
            new_name='cart_product',
        ),
        migrations.RenameField(
            model_name='cartproductmapping',
            old_name='cart_qty',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='cart_products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_product_shipment', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_shipment',
            field=models.ManyToManyField(related_name='order_shipment_mapping', to='gram_to_brand.CarOrderShipmentMapping'),
        ),
    ]
