# Generated by Django 2.2 on 2022-06-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0004_cart_po_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproductmapping',
            name='gst',
        ),
    ]
