# Generated by Django 2.1 on 2018-10-15 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0005_auto_20181015_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cart', to='shops.Shop'),
        ),
    ]
