# Generated by Django 2.2 on 2022-06-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0005_remove_cartproductmapping_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmapping',
            name='gst',
            field=models.IntegerField(blank=True, choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], null=True),
        ),
    ]
