# Generated by Django 2.1 on 2018-10-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0006_auto_20181015_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='order_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('ordered_to_brand', 'Ordered To Brand'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
