# Generated by Django 2.2 on 2022-06-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0006_cartproductmapping_gst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproductmapping',
            name='cess',
        ),
    ]
