# Generated by Django 2.2 on 2022-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0007_remove_cartproductmapping_cess'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmapping',
            name='cess',
            field=models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True),
        ),
    ]
