# Generated by Django 2.2 on 2022-06-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0008_cartproductmapping_cess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnorder',
            name='tcs_amount',
        ),
    ]
