# Generated by Django 2.1 on 2018-10-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0009_auto_20181015_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='grn_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_order_grn_order_product', to='gram_to_brand.GRNOrder'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
