# Generated by Django 2.2 on 2022-06-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0009_remove_grnorder_tcs_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorder',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
    ]
