# Generated by Django 2.1 on 2018-10-15 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('gram_to_brand', '0010_auto_20181015_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 15, 15, 51, 58, 617094)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_cart', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grnorder',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_grn_order', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_grn_order_product', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 15, 15, 52, 6, 90816)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_order', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
