# Generated by Django 2.1 on 2018-10-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0012_auto_20181015_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnorder',
            name='grn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
