# Generated by Django 2.2 on 2022-06-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0012_grnorder_total_freight_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnorder',
            name='discount_charges',
        ),
    ]
