# Generated by Django 2.2 on 2022-06-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0014_grnorder_discount_charges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnorder',
            name='discount_charges',
        ),
        migrations.RemoveField(
            model_name='grnorder',
            name='insurance_charges',
        ),
        migrations.RemoveField(
            model_name='grnorder',
            name='other_charges',
        ),
        migrations.RemoveField(
            model_name='grnorder',
            name='total_grn_amount',
        ),
    ]
