# Generated by Django 2.2 on 2022-06-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0015_auto_20220602_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorder',
            name='discount_charges',
            field=models.DecimalField(decimal_places=4, default='0.0000', max_digits=20),
        ),
    ]
