# Generated by Django 2.1 on 2018-10-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0015_auto_20181016_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='damaged_total_qty',
            new_name='total_damaged_qty',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='delivered_total_qty',
            new_name='total_delivered_qty',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='returned_total_qty',
            new_name='total_returned_qty',
        ),
    ]
