# Generated by Django 2.1 on 2018-10-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0016_auto_20181016_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='changed_price',
            field=models.FloatField(default=0),
        ),
    ]
