# Generated by Django 2.2 on 2022-06-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0018_auto_20220602_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='barcode_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='product_invoice_gst',
            field=models.IntegerField(choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], default=0, null=True),
        ),
    ]
