# Generated by Django 2.1 on 2018-10-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0003_auto_20181017_1147'),
        ('addresses', '0003_auto_20181010_1702'),
        ('products', '0009_productpricecsv_area'),
        ('gram_to_brand', '0018_remove_orderitem_changed_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRNOrderProductHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('grn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_price', models.FloatField(default=0)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('available_qty', models.PositiveIntegerField(default=0)),
                ('ordered_qty', models.PositiveIntegerField(default=0)),
                ('delivered_qty', models.PositiveIntegerField(default=0)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grn_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_order_grn_order_product_history', to='gram_to_brand.GRNOrder')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_grn_order_product_history', to='accounts.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_grn_order_history', to='gram_to_brand.Order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_grn_order_history', to='gram_to_brand.OrderItem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_grn_order_product_history', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mrp', models.FloatField(default=0)),
                ('total_discount_amount', models.FloatField(default=0)),
                ('total_tax_amount', models.FloatField(default=0)),
                ('total_final_amount', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('ordered_to_brand', 'Ordered To Brand'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_order_history', to='addresses.Address')),
                ('buyer_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gf_buyer_shop_order_history', to='shops.Shop')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_order_modified_user_history', to='accounts.User')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_order_by_user_history', to='accounts.User')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address_cart', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='buyer_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shop_order', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='cart',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_cart', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_cart', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='available_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='ordered_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='ordered_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart_mapping_history', to='gram_to_brand.Cart'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_received_by_user_history', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='seller_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gf_seller_shop_order_history', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address_order_history', to='addresses.Address'),
        ),
    ]
