# Generated by Django 2.1 on 2018-11-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_address_shop_name'),
        ('gram_to_brand', '0019_auto_20181023_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'PO Generation'},
        ),
        migrations.AlterModelOptions(
            name='cartproductmapping',
            options={'verbose_name': 'PO Generation Mapping'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='buyer_shop',
            new_name='supplier',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='city',
        ),
        migrations.AddField(
            model_name='cart',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_cart', to='addresses.State'),
        ),
    ]
