# Generated by Django 2.2 on 2022-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0020_remove_grnorderproductmapping_barcode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='barcode_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
