# Generated by Django 2.1 on 2018-11-22 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181029_1442'),
        ('gram_to_brand', '0020_auto_20181110_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='supplier',
            new_name='brand_supplier',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='billing_address',
            new_name='gf_billing_address',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='shipping_address',
            new_name='gf_shipping_address',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cart_status',
            new_name='po_status',
        ),
        migrations.AddField(
            model_name='cart',
            name='po_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='po_creation_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 11, 22, 12, 9, 32, 111337)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='po_raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_raise_user_cart', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='po_validity_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 22, 12, 9, 42, 419989)),
            preserve_default=False,
        ),
    ]
