# Generated by Django 2.1 on 2018-11-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0021_auto_20181122_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproductmapping',
            options={'verbose_name': 'Select Product'},
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartproductmapping',
            name='scheme',
            field=models.FloatField(blank=True, default=0, help_text='data into percentage %', null=True),
        ),
    ]
