# Generated by Django 2.1 on 2018-11-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0022_auto_20181122_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_id',
            new_name='po_no',
        ),
    ]
