# Generated by Django 2.2 on 2022-06-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0024_auto_20220602_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grnorderproductmapping',
            name='cess_percentage',
        ),
    ]
