# Generated by Django 2.1 on 2018-11-22 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20181029_1442'),
        ('gram_to_brand', '0024_grnorder_grn_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grn_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_order_brand_note', to='gram_to_brand.GRNOrder')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_user_brand_note', to='accounts.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_brand_note', to='gram_to_brand.Order')),
            ],
        ),
        migrations.RenameField(
            model_name='grnorderproductmapping',
            old_name='changed_price',
            new_name='product_invoice_price',
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='product_invoice_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_item', to='gram_to_brand.Order', verbose_name='po no'),
        ),
    ]
