# Generated by Django 2.1 on 2018-11-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0025_auto_20181122_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnorder',
            options={'verbose_name': 'Add Edit GRN Order'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Purchase Order Item List'},
        ),
    ]
