# Generated by Django 2.2 on 2022-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0025_remove_grnorderproductmapping_cess_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='cess_percentage',
            field=models.IntegerField(blank=True, choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True),
        ),
    ]
