# Generated by Django 2.2 on 2022-06-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0027_remove_grnorderproductmapping_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='product_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
