# Generated by Django 2.2 on 2022-06-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0028_grnorderproductmapping_product_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='po_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=50),
        ),
    ]
