# Generated by Django 2.1 on 2018-11-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0029_auto_20181123_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_grn_order', to='gram_to_brand.Order', verbose_name='po no'),
        ),
    ]
