# Generated by Django 2.1 on 2018-11-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0030_auto_20181123_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='state',
            new_name='supplier_state',
        ),
        migrations.AlterField(
            model_name='cart',
            name='supplier_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_vendor_order', to='brand.Vendor'),
        ),
    ]
