# Generated by Django 2.1 on 2018-11-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0031_auto_20181129_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='already_grned_product',
            field=models.PositiveIntegerField(default=0, verbose_name='Already GRNed Product Quantity'),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='po_product_price',
            field=models.FloatField(default=0, verbose_name='PO Product Price'),
        ),
        migrations.AddField(
            model_name='grnorderproductmapping',
            name='po_product_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='PO Product Quantity'),
        ),
    ]
