# Generated by Django 2.1 on 2018-11-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0001_initial'),
        ('products', '0013_merge_20181129_1230'),
        ('gram_to_brand', '0031_auto_20181129_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProductReserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_qty', models.PositiveIntegerField(default=0)),
                ('order_reserve_end_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiler_ordered_retailer_cart', to='retailer_to_gram.Cart')),
                ('order_product_reserved', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiler_order_product_order_product_reserved', to='gram_to_brand.GRNOrderProductMapping')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiler_product_order_product_reserved', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_order', to='gram_to_brand.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PickListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_qty', models.PositiveIntegerField(default=0)),
                ('return_qty', models.PositiveIntegerField(default=0)),
                ('damage_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('grn_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_cart', to='gram_to_brand.GRNOrder')),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_items_pick_list', to='gram_to_brand.PickList')),
            ],
        ),
    ]
