# Generated by Django 2.1 on 2018-11-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20181129_1230'),
        ('gram_to_brand', '0032_orderedproductreserved_picklist_picklistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklistitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_product', to='products.Product'),
        ),
    ]
