# Generated by Django 2.1 on 2018-12-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0002_auto_20181201_0031'),
        ('gram_to_brand', '0033_picklistitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='picklist',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_cart', to='retailer_to_gram.Cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picklist',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_order', to='retailer_to_gram.Order'),
        ),
    ]
