# Generated by Django 2.1 on 2018-12-01 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0035_picklist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklistitems',
            name='grn_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_list_cart', to='gram_to_brand.GRNOrder', verbose_name='GRN No'),
        ),
    ]
