# Generated by Django 2.1 on 2018-12-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0036_auto_20181201_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grnorder',
            options={},
        ),
        migrations.AddField(
            model_name='brandnote',
            name='brand_note_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
