# Generated by Django 2.1 on 2018-12-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0032_auto_20181130_1202'),
        ('gram_to_brand', '0036_auto_20181201_1622'),
    ]

    operations = [
    ]
