# Generated by Django 2.1 on 2018-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0037_auto_20181211_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_product_mapping_csv',
            field=models.FileField(default='csv', upload_to='gram/brand/cart_product_mapping_csv'),
        ),
    ]
