# Generated by Django 2.1 on 2018-12-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0038_cart_cart_product_mapping_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_product_mapping_csv',
            field=models.FileField(upload_to='gram/brand/cart_product_mapping_csv'),
        ),
    ]
