# Generated by Django 2.1 on 2018-12-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0039_auto_20181205_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproductmapping',
            old_name='qty',
            new_name='number_of_cases',
        ),
    ]
