# Generated by Django 2.1 on 2018-12-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0040_auto_20181205_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproductmapping',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
