# Generated by Django 2.1 on 2018-12-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0037_auto_20181211_1706'),
        ('gram_to_brand', '0041_cartproductmapping_qty'),
    ]

    operations = [
    ]
