# Generated by Django 2.1 on 2018-12-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0042_merge_20181213_1715'),
        ('gram_to_brand', '0039_auto_20181213_1322'),
    ]

    operations = [
    ]
