# Generated by Django 2.1 on 2018-12-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0043_merge_20181213_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_product_mapping_csv',
            field=models.FileField(blank=True, null=True, upload_to='gram/brand/cart_product_mapping_csv'),
        ),
    ]
