# Generated by Django 2.1 on 2018-12-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_to_brand', '0044_auto_20181213_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductmapping',
            name='number_of_cases',
            field=models.PositiveIntegerField(),
        ),
    ]
