# Generated by Django 2.1 on 2022-04-04 16:24

import adminsortable.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2cCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_sku_part', models.CharField(help_text='Please enter three characters for SKU', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')])),
                ('category_image', models.FileField(blank=True, null=True, upload_to='b2c_category_img_file')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_cat_parent', to='categories.B2cCategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='b2c_category_updated_by', to='accounts.User')),
            ],
            options={
                'verbose_name_plural': 'B2C Categories',
            },
        ),
        migrations.CreateModel(
            name='B2cCategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_data_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('category_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_category_posation_data', to='categories.B2cCategory')),
            ],
            options={
                'ordering': ['category_data_order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_desc', models.TextField(blank=True, null=True)),
                ('category_sku_part', models.CharField(help_text='Please enter three characters for SKU', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')])),
                ('category_image', models.FileField(blank=True, null=True, upload_to='category_img_file')),
                ('b2c_status', models.BooleanField(default=True)),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_parent', to='categories.Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_updated_by', to='accounts.User')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CategoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_data_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('category_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_posation_data', to='categories.Category')),
            ],
            options={
                'ordering': ['category_data_order'],
            },
        ),
        migrations.CreateModel(
            name='CategoryPosation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posation_name', models.CharField(max_length=255)),
                ('category_posation_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Category Position',
                'verbose_name_plural': 'Category Positions',
                'ordering': ['category_posation_order'],
            },
        ),
        migrations.AddField(
            model_name='categorydata',
            name='category_pos',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_data', to='categories.CategoryPosation'),
        ),
        migrations.AddField(
            model_name='b2ccategorydata',
            name='category_pos',
            field=adminsortable.fields.SortableForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_cat_data', to='categories.CategoryPosation'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_slug', 'category_parent')},
        ),
        migrations.AlterUniqueTogether(
            name='b2ccategory',
            unique_together={('category_slug', 'category_parent')},
        ),
    ]
