# Generated by Django 2.1 on 2018-09-26 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='sub_category_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_parent', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_sku_part',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_slug', 'category_parent')},
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
