# Generated by Django 2.1 on 2018-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(blank=True, null=True, upload_to='category_img'),
        ),
    ]
