# Generated by Django 2.2 on 2022-06-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20220602_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_name', 'category_type'), ('category_slug', 'category_parent')},
        ),
    ]
