# Generated by Django 2.1 on 2018-09-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20180926_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorydata',
            old_name='category',
            new_name='category_pos',
        ),
    ]
