# Generated by Django 2.1 on 2018-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20181010_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(blank=True, null=True, upload_to='category_img_file'),
        ),
    ]
