# Generated by Django 2.2 on 2022-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20220602_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='b2c_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_slug', 'category_parent')},
        ),
        migrations.DeleteModel(
            name='CategoryDisplayOrder',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
