# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0004_auto_20220617_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category_slug', 'category_parent'), ('category_name', 'category_type')},
        ),
        migrations.CreateModel(
            name='CategoryDisplayOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('order_no', models.PositiveIntegerField(default=0)),
                ('category', models.OneToOneField(limit_choices_to={'category_type': 'superstore'}, on_delete=django.db.models.deletion.CASCADE, related_name='category_view_order', to='categories.Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Category Display Order',
                'verbose_name_plural': 'Category Display Orders',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='b2c_status',
        ),
    ]
