# Generated by Django 2.2 on 2022-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_auto_20220617_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
