# Generated by Django 2.1 on 2018-12-05 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_auto_20181205_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_sku_part',
            field=models.CharField(help_text='Please enter three characters for SKU', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')]),
        ),
    ]
