# Generated by Django 2.1 on 2018-10-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer_type_name', models.CharField(max_length=255)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('shop_billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_add_shop', to='addresses.Address')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_owner_shop', to='accounts.User')),
                ('shop_shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_add_shop', to='addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer')], default='r', max_length=50)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('shop_sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_sub_type_shop', to='shops.RetailerType')),
            ],
        ),
        migrations.CreateModel(
            name='SpRetailerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiler_mapping', to='shops.Shop')),
                ('service_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_mapping', to='shops.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_tyoe_shop', to='shops.ShopType'),
        ),
    ]
