# Generated by Django 2.1 on 2018-10-08 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retailertype',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='retailertype',
            old_name='is_modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='is_modified',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='shoptype',
            old_name='is_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='shoptype',
            old_name='is_modified',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='spretailermapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spretailermapping',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spretailermapping',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
