# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='enable_loyalty_points',
        ),
    ]
