# Generated by Django 2.1 on 2018-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20181010_1702'),
        ('shops', '0002_auto_20181008_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_shop', to='addresses.Area'),
        ),
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_shop', to='addresses.City'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_type_shop', to='shops.ShopType'),
        ),
    ]
