# Generated by Django 2.1 on 2022-04-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_remove_shop_enable_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='enable_loyalty_points',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
