# Generated by Django 2.1 on 2022-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_enable_loyalty_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='enable_loyalty_points',
            field=models.BooleanField(default=True),
        ),
    ]
