# Generated by Django 2.1 on 2018-10-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20181017_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_photo', models.FileField(upload_to='shop_photos/shop_name/')),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_name_photos', to='shops.Shop')),
            ],
        ),
    ]
