# Generated by Django 2.1 on 2022-04-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20220404_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='enable_loyalty_points',
            field=models.BooleanField(default=False),
        ),
    ]
