# Generated by Django 2.1 on 2018-10-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopphotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_document_type', models.CharField(choices=[('gstin', 'GSTIN'), ('sln', 'Shop License Number'), ('uidai', 'Aadhaar Card'), ('bill', 'Shop Electricity Bill')], default='gstin', max_length=100)),
                ('shop_document_number', models.CharField(max_length=100)),
                ('shop_document_photo', models.FileField(upload_to='shop_photos/shop_name/documents/')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopdocuments',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_name_documents', to='shops.Shop'),
        ),
    ]
