# Generated by Django 2.1 on 2018-10-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20181023_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopDocuments',
            new_name='ShopDocument',
        ),
        migrations.RenameModel(
            old_name='ShopPhotos',
            new_name='ShopPhoto',
        ),
    ]
