# Generated by Django 2.1 on 2022-04-14 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20220406_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivefeedback',
            name='day_beat_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_beat_plan', to='shops.DayBeatPlanning', unique=True),
        ),
    ]
