# Generated by Django 2.1 on 2018-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20181023_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailertype',
            name='retailer_type_name',
            field=models.CharField(choices=[('gm', 'General Merchant'), ('ps', 'Pan Shop')], default='gm', max_length=100),
        ),
    ]
