# Generated by Django 2.1 on 2022-04-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20220414_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('shops.shop',),
        ),
    ]
