# Generated by Django 2.1 on 2022-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_shopconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopConfig',
        ),
        migrations.AddField(
            model_name='shop',
            name='status_reward_configuration',
            field=models.BooleanField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive'),
        ),
    ]
