# Generated by Django 2.1 on 2018-10-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20181026_1535'),
        ('shops', '0007_auto_20181024_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAddressMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('shop_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_address_address_mapping', to='addresses.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='area',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_billing_address',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_shipping_address',
        ),
        migrations.AddField(
            model_name='shopaddressmapping',
            name='shop_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_name_address_mapping', to='shops.Shop'),
        ),
    ]
