# Generated by Django 2.1 on 2018-10-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20181026_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopaddressmapping',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='shopaddressmapping',
            name='shop_name',
        ),
        migrations.AlterField(
            model_name='retailertype',
            name='retailer_type_name',
            field=models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer')], default='r', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='shop_type',
            field=models.CharField(choices=[('gm', 'General Merchant'), ('ps', 'Pan Shop')], default='gm', max_length=50),
        ),
        migrations.DeleteModel(
            name='ShopAddressMapping',
        ),
    ]
