# Generated by Django 2.1 on 2022-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20220419_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='status_reward_configuration',
        ),
    ]
