# Generated by Django 2.1 on 2018-10-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20181029_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailertype',
            name='retailer_type_name',
            field=models.CharField(choices=[('gm', 'General Merchant'), ('ps', 'Pan Shop')], default='gm', max_length=100),
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='shop_type',
            field=models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer')], default='r', max_length=50),
        ),
    ]
