# Generated by Django 2.1 on 2022-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_remove_shop_status_reward_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='status_reward_configuration',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20),
        ),
    ]
