# Generated by Django 2.1 on 2018-11-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20181031_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoptype',
            name='shop_type',
            field=models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer'), ('b', 'Brand'), ('gf', 'Gram Factory')], default='r', max_length=50),
        ),
    ]
