# Generated by Django 2.1 on 2018-11-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_auto_20181123_1136'),
        ('shops', '0011_auto_20181112_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_brand', to='brand.Brand'),
        ),
    ]
