# Generated by Django 2.1 on 2022-04-19 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shop_status_reward_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fofoconfigsubcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fofo_category_details', to='shops.FOFOConfigCategory'),
        ),
    ]
