# Generated by Django 2.1 on 2022-04-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20220419_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fofoconfigsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fofo_category_details', to='shops.FOFOConfigCategory'),
        ),
    ]
