# Generated by Django 2.1 on 2018-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_shop_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='brand',
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='shop_type',
            field=models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer')], default='r', max_length=50),
        ),
    ]
