# Generated by Django 2.1 on 2022-04-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20220420_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='status_reward_configuration',
        ),
    ]
