# Generated by Django 2.1 on 2018-11-30 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20181128_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentRetailerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrent_mapping', to='shops.Shop')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiler_mapping', to='shops.Shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='spretailermapping',
            name='retailer',
        ),
        migrations.RemoveField(
            model_name='spretailermapping',
            name='service_partner',
        ),
        migrations.AlterField(
            model_name='shoptype',
            name='shop_type',
            field=models.CharField(choices=[('sp', 'Service Partner'), ('r', 'Retailer'), ('sr', 'Super Retailer'), ('gf', 'Gram Factory')], default='r', max_length=50),
        ),
        migrations.DeleteModel(
            name='SpRetailerMapping',
        ),
        migrations.AlterUniqueTogether(
            name='parentretailermapping',
            unique_together={('parent', 'retailer')},
        ),
    ]
