# Generated by Django 2.1 on 2018-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20181130_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentretailermapping',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
