# Generated by Django 2.1 on 2022-05-05 15:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_shopfcmtopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopfcmtopic',
            name='registration_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None),
        ),
    ]
