# Generated by Django 2.1 on 2018-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_parentretailermapping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentretailermapping',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
