# Generated by Django 2.1 on 2022-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20220505_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='superstore_enable',
            field=models.BooleanField(default=False),
        ),
    ]
