# Generated by Django 2.1 on 2018-12-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_auto_20181204_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentretailermapping',
            unique_together=set(),
        ),
    ]
