# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20220617_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_code_super_store',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='superstore_enable',
            field=models.BooleanField(default=False),
        ),
    ]
