# Generated by Django 2.1 on 2022-04-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20220414_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posstorerewardmapping',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='posstorerewardmapping',
            name='modified_at',
        ),
    ]
