# Generated by Django 2.1 on 2022-04-14 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20220414_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 14, 17, 9, 19, 636798)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
