# Generated by Django 2.1 on 2022-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20220414_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posstorerewardmapping',
            name='is_active',
        ),
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='status',
            field=models.BooleanField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive'),
        ),
    ]
