# Generated by Django 2.1 on 2022-04-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20220414_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posstorerewardmapping',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=50),
        ),
    ]
