# Generated by Django 2.1 on 2022-04-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20220414_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20),
        ),
    ]
