# Generated by Django 2.1 on 2022-04-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20220414_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='is_max_redeem_point_ecom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='is_max_redeem_point_pos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='is_point_add_ecom_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posstorerewardmapping',
            name='is_point_add_pos_order',
            field=models.BooleanField(default=True),
        ),
    ]
