# Generated by Django 2.1 on 2022-04-18 13:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import shops.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20220414_1706'),
        ('pos', '0010_auto_20220417_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfigKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', shops.fields.CaseInsensitiveCharField(max_length=125, unique=True)),
                ('type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean')], default='int', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShopRewardConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_config_key', to='pos.ShopConfigKey', unique=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_reward_config', to='shops.Shop', unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shoprewardconfig',
            unique_together={('shop', 'key')},
        ),
    ]
