# Generated by Django 2.1 on 2022-04-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_auto_20220418_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprewardconfig',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_config_key', to='pos.ShopConfigKey'),
        ),
    ]
