# Generated by Django 2.1 on 2022-04-18 15:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_auto_20220418_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRewardConfigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_config_key', to='pos.ShopConfigKey')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='shoprewardconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shoprewardconfigration',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ShopRewardConfig'),
        ),
        migrations.RemoveField(
            model_name='shoprewardconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoprewardconfig',
            name='key',
        ),
        migrations.RemoveField(
            model_name='shoprewardconfig',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='shoprewardconfig',
            name='value',
        ),
        migrations.AlterUniqueTogether(
            name='shoprewardconfigration',
            unique_together={('shop', 'key')},
        ),
    ]
