# Generated by Django 2.1 on 2022-04-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_auto_20220418_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprewardconfig',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=20),
        ),
    ]
