# Generated by Django 2.1 on 2022-04-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_auto_20220418_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoprewardconfigration',
            old_name='shop',
            new_name='shop_config',
        ),
        migrations.AlterUniqueTogether(
            name='shoprewardconfigration',
            unique_together={('shop_config', 'key')},
        ),
    ]
