# Generated by Django 2.1 on 2022-04-18 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20220418_1633'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posstorerewardmapping',
            options={'verbose_name': 'POS Store Reward Mappings'},
        ),
        migrations.AlterModelOptions(
            name='shoprewardconfig',
            options={'verbose_name': 'POS Store Reward Mapping'},
        ),
    ]
