# Generated by Django 2.1 on 2022-04-19 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_auto_20220419_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprewardconfigration',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_config_key', to='pos.ShopConfigKey'),
        ),
    ]
