# Generated by Django 2.1 on 2022-04-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_posstorerewardmappings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PosStoreRewardMappings',
        ),
    ]
