# Generated by Django 2.1 on 2022-04-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_shop_status_reward_configuration'),
        ('pos', '0021_delete_posstorerewardmappings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosStoreRewardMappings',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('shops.shop',),
        ),
    ]
