# Generated by Django 2.1 on 2022-04-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_posstorerewardmappings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posstorerewardmapping',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoprewardconfig',
            name='shop',
        ),
        migrations.AlterUniqueTogether(
            name='shoprewardconfigration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoprewardconfigration',
            name='key',
        ),
        migrations.RemoveField(
            model_name='shoprewardconfigration',
            name='shop_config',
        ),
        migrations.DeleteModel(
            name='PosStoreRewardMapping',
        ),
        migrations.DeleteModel(
            name='ShopConfigKey',
        ),
        migrations.DeleteModel(
            name='ShopRewardConfig',
        ),
        migrations.DeleteModel(
            name='ShopRewardConfigration',
        ),
    ]
