# Generated by Django 2.2 on 2022-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_retailerproduct_online_disabled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscart',
            name='po_type',
            field=models.CharField(blank=True, choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='postrip',
            name='trip_type',
            field=models.CharField(choices=[('ECOM', 'Ecom'), ('SUPERSTORE', 'SUPERSTORE')], max_length=10),
        ),
    ]
