# Generated by Django 2.2 on 2022-06-09 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_sp', '0015_orderedproduct_shipment_label_pdf'),
        ('pos', '0033_auto_20220609_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrip',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pos_trips', to='retailer_to_sp.OrderedProduct'),
        ),
        migrations.AddField(
            model_name='postrip',
            name='trip_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postrip',
            name='trip_start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postrip',
            name='trip_type',
            field=models.CharField(choices=[('ECOM', 'Ecom'), ('SUPERSTORE', 'SUPERSTORE')], max_length=10, null=True),
        ),
    ]
