# Generated by Django 2.2 on 2022-06-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_auto_20220609_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrip',
            name='shipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pos_trips', to='retailer_to_sp.OrderedProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postrip',
            name='trip_type',
            field=models.CharField(choices=[('ECOM', 'Ecom'), ('SUPERSTORE', 'SUPERSTORE')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
