# Generated by Django 2.2 on 2022-06-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_auto_20220610_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrip',
            name='trip_type',
            field=models.CharField(choices=[('ECOM', 'Ecom')], max_length=10),
        ),
    ]
