# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_auto_20220617_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrip',
            name='trip_type',
            field=models.CharField(choices=[('ECOM', 'Ecom'), ('SUPERSTORE', 'SUPERSTORE')], max_length=10),
        ),
    ]
