# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCancelledPicklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order_no', models.CharField(max_length=20)),
                ('is_picklist_refreshed', models.BooleanField(default=False, verbose_name='Picklist Refreshed')),
            ],
            options={
                'verbose_name': 'Audit Cancelled Picklist',
                'verbose_name_plural': 'Audit Cancelled Picklists',
                'db_table': 'wms_audit_cancelled_picklists',
            },
        ),
        migrations.CreateModel(
            name='AuditDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('audit_no', models.CharField(max_length=10, null=True)),
                ('audit_run_type', models.PositiveSmallIntegerField(choices=[(0, 'Manual'), (2, 'Automated')], verbose_name='Audit Run Type')),
                ('audit_inventory_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'warehouse'), (2, 'bin'), (3, 'bin-warehouse'), (4, 'daily operations')], null=True, verbose_name='Audit Inventory Type')),
                ('audit_level', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Bin Wise'), (1, 'Product Wise')], null=True, verbose_name='Audit Type')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='Audit Status')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Initiated'), (3, 'Ended'), (4, 'Pass'), (5, 'Fail'), (6, 'Ticket Raised'), (7, 'Ticket Closed')], default=1, verbose_name='Audit State')),
                ('is_historic', models.BooleanField(default=False)),
                ('audit_from', models.DateField(blank=True, null=True, verbose_name='Start Audit From')),
                ('pbi', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Audit Tasks',
                'db_table': 'wms_audit_details',
            },
        ),
        migrations.CreateModel(
            name='AuditedBinRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'wms_audit_bin_record',
            },
        ),
        migrations.CreateModel(
            name='AuditedProductRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'db_table': 'wms_audit_product_record',
            },
        ),
        migrations.CreateModel(
            name='AuditNumberGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('audit_run_type', models.PositiveSmallIntegerField(choices=[(0, 'Manual'), (2, 'Automated')])),
                ('audit_level', models.PositiveSmallIntegerField(choices=[(0, 'Bin Wise'), (1, 'Product Wise')], null=True)),
                ('current_number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Released'), (1, 'Blocked')])),
            ],
            options={
                'db_table': 'wms_audit_products',
            },
        ),
        migrations.CreateModel(
            name='AuditRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In Progress'), (1, 'Aborted'), (2, 'Completed')])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Audits Performed',
                'db_table': 'wms_audit_run_log',
            },
        ),
        migrations.CreateModel(
            name='AuditRunItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('qty_expected', models.PositiveIntegerField()),
                ('qty_calculated', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Dirty'), (1, 'Clean')])),
            ],
            options={
                'db_table': 'wms_audit_run_items',
            },
        ),
        migrations.CreateModel(
            name='AuditTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('batch_id', models.CharField(max_length=50, null=True)),
                ('qty_expected_type', models.PositiveIntegerField(choices=[(0, 'bin'), (1, 'bin-calculated'), (2, 'warehouse'), (3, 'warehouse-calculated')])),
                ('qty_calculated_type', models.PositiveIntegerField(choices=[(0, 'bin'), (1, 'bin-calculated'), (2, 'warehouse'), (3, 'warehouse-calculated')])),
                ('qty_expected', models.PositiveIntegerField()),
                ('qty_calculated', models.IntegerField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Assigned'), (2, 'Closed')])),
            ],
            options={
                'verbose_name': 'Automated Audit Ticket',
                'verbose_name_plural': 'Automated Audit Tickets',
                'db_table': 'wms_audit_tickets',
            },
        ),
        migrations.CreateModel(
            name='AuditTicketManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('batch_id', models.CharField(max_length=50, null=True)),
                ('qty_normal_system', models.PositiveIntegerField(verbose_name='Normal System Qty')),
                ('qty_normal_actual', models.PositiveIntegerField(verbose_name='Normal Physical Qty')),
                ('qty_damaged_system', models.PositiveIntegerField(verbose_name='Damaged System Qty')),
                ('qty_damaged_actual', models.PositiveIntegerField(verbose_name='Damaged Physical Qty')),
                ('qty_expired_system', models.PositiveIntegerField(verbose_name='Expired System Qty')),
                ('qty_expired_actual', models.PositiveIntegerField(verbose_name='Expired Physical Qty')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Assigned'), (2, 'Closed')])),
            ],
            options={
                'verbose_name': 'Manual Audit Ticket',
                'verbose_name_plural': 'Manual Audit Tickets',
                'db_table': 'wms_audit_tickets_manual',
            },
        ),
        migrations.CreateModel(
            name='AuditUpdatedPickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('order_no', models.CharField(max_length=20)),
                ('batch_id', models.CharField(max_length=50)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.AuditDetail')),
            ],
            options={
                'verbose_name': 'Audit Updated Pickup',
                'verbose_name_plural': 'Audit Updated Pickups',
                'db_table': 'wms_audit_updated_pickups',
            },
        ),
    ]
