# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('wms', '0001_initial'),
        ('shops', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditupdatedpickup',
            name='bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditticketmanual',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.User', verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='auditticketmanual',
            name='audit_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditRun'),
        ),
        migrations.AddField(
            model_name='auditticketmanual',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditticketmanual',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='auditticketmanual',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='audit_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditRun'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='inventory_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.InventoryState'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='inventory_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.InventoryType'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='auditticket',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='audit_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditRun'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='inventory_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.InventoryState'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='inventory_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wms.InventoryType'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='auditrunitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='archive_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.InventoryArchiveMaster'),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit.AuditDetail'),
        ),
        migrations.AddField(
            model_name='auditrun',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditproduct',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.AuditDetail'),
        ),
        migrations.AddField(
            model_name='auditproduct',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rt_audit_sku', to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='auditproduct',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditedproductrecord',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.AuditDetail'),
        ),
        migrations.AddField(
            model_name='auditedproductrecord',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.Product', to_field='product_sku'),
        ),
        migrations.AddField(
            model_name='auditedbinrecord',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.AuditDetail'),
        ),
        migrations.AddField(
            model_name='auditedbinrecord',
            name='bin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditdetail',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audits_assigned', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='auditdetail',
            name='bin',
            field=models.ManyToManyField(blank=True, null=True, related_name='audit_bin_mapping', to='wms.Bin'),
        ),
        migrations.AddField(
            model_name='auditdetail',
            name='sku',
            field=models.ManyToManyField(blank=True, null=True, related_name='audit_product_mapping', to='products.Product'),
        ),
        migrations.AddField(
            model_name='auditdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='audits_created', to='accounts.User', verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='auditdetail',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='auditcancelledpicklist',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='audit.AuditDetail'),
        ),
    ]
