# Generated by Django 2.1 on 2018-10-18 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0009_productpricecsv_area'),
        ('sp_to_gram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_last_modified_user_order', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_price', models.FloatField(default=0)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('shipped_qty', models.PositiveIntegerField(default=0)),
                ('delivered_qty', models.PositiveIntegerField(default=0)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_last_modified_user_order_product', to='accounts.User')),
                ('ordered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_order_product_order_product_mapping', to='sp_to_gram.OrderedProduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_product_order_product', to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='cartproductmapping',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_order_modified_user', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_ordered_by_user', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_received_by_user', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_order_order_product', to='sp_to_gram.Order'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_ordered_product_received_by_user', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='shipped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_shipped_product_ordered_by_user', to='accounts.User'),
        ),
    ]
