# Generated by Django 2.1 on 2018-10-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0002_auto_20181018_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproductmapping',
            name='changed_price',
        ),
        migrations.RemoveField(
            model_name='orderedproductmapping',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='orderedproductmapping',
            name='manufacture_date',
        ),
    ]
