# Generated by Django 2.1 on 2018-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0003_auto_20181018_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(blank=True, choices=[('ordered_to_gram', 'Ordered To Gramfactory'), ('order_shipped', 'Order Shipped From Gramfactory'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ordered_to_gram', 'Ordered To Gramfactory'), ('order_shipped', 'Order Shipped From Gramfactory'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50),
        ),
    ]
