# Generated by Django 2.1 on 2018-10-23 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20181010_1702'),
        ('sp_to_gram', '0004_auto_20181018_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_billing_address_cart', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_shipping_address_cart', to='addresses.Address'),
        ),
        migrations.AddField(
            model_name='orderedproductmapping',
            name='available_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedproductmapping',
            name='ordered_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderedproductmapping',
            name='reserved_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
