# Generated by Django 2.1 on 2018-10-29 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0006_auto_20181025_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproductreserved',
            name='order_reserve_end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 11, 6, 21, 997867)),
        ),
        migrations.AddField(
            model_name='orderedproductreserved',
            name='order_reserve_start_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 29, 11, 4, 41, 709527)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedproductreserved',
            name='order_reserve_status',
            field=models.BooleanField(default=False),
        ),
    ]
