# Generated by Django 2.1 on 2018-10-29 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0009_auto_20181029_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductreserved',
            name='order_reserve_end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 15, 16, 51, 400339)),
        ),
    ]
