# Generated by Django 2.1 on 2018-10-30 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0010_auto_20181029_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductreserved',
            name='order_reserve_end_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 0, 28, 9, 654511)),
        ),
    ]
