# Generated by Django 2.1 on 2018-10-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0012_auto_20181030_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproductreserved',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp_ordered_retailer_cart', to='retailer_to_sp.Cart'),
        ),
    ]
