# Generated by Django 2.1 on 2018-10-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0015_auto_20181030_1515'),
        ('sp_to_gram', '0012_auto_20181030_1612'),
    ]

    operations = [
    ]
