# Generated by Django 2.1 on 2018-10-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_to_gram', '0017_auto_20181030_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproductmapping',
            name='reserved_qty',
        ),
        migrations.RemoveField(
            model_name='orderedproductreserved',
            name='order_reserve_start_time',
        ),
        migrations.RemoveField(
            model_name='orderedproductreserved',
            name='order_reserve_status',
        ),
    ]
