# Generated by Django 2.1 on 2022-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0003_auto_20220414_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevice',
            name='app_type',
            field=models.CharField(choices=[('pos', 'Pos App'), ('ecom', 'Ecom App')], default='pos', max_length=20),
        ),
    ]
