# Generated by Django 2.1 on 2022-05-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_center', '0004_fcmdevice_app_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='dev_id',
            field=models.CharField(max_length=50, verbose_name='Device ID'),
        ),
        migrations.AlterUniqueTogether(
            name='fcmdevice',
            unique_together={('dev_id', 'app_type')},
        ),
    ]
