# Generated by Django 2.1 on 2018-11-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0007_address_shop_name'),
        ('products', '0010_auto_20181110_1927'),
        ('accounts', '0003_auto_20181029_1442'),
        ('shops', '0012_shop_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cart_status', models.CharField(blank=True, choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_last_modified_user_cart', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='CartProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('qty_error_msg', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtg_cart_list', to='retailer_to_gram.Cart')),
                ('cart_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtg_cart_product_mapping', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('debit_note', 'Debit Note'), ('credit_note', 'Credit Note')], max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_last_modified_user_note', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('total_mrp', models.FloatField(default=0)),
                ('total_discount_amount', models.FloatField(default=0)),
                ('total_tax_amount', models.FloatField(default=0)),
                ('total_final_amount', models.FloatField(default=0)),
                ('order_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('deleted', 'Deleted'), ('ordered_to_sp', 'Ordered To Service Partner'), ('order_shipped', 'Order Shipped From Service Partner'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered')], max_length=50)),
                ('payment_mode', models.CharField(choices=[('cash_in_delivery', 'Cash In Delivery'), ('neft', 'NEFT')], max_length=255)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.FloatField(default=0)),
                ('payment_status', models.CharField(blank=True, choices=[('done', 'Done'), ('pending', 'Pending')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_billing_address_order', to='addresses.Address')),
                ('buyer_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_buyer_shop_order', to='shops.Shop')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_modified_user', to='accounts.User')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_ordered_by_user', to='accounts.User')),
                ('ordered_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_cart_mapping', to='retailer_to_gram.Cart')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_received_by_user', to='accounts.User')),
                ('seller_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_seller_shop_order', to='shops.Shop')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_shipping_address_order', to='addresses.Address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_last_modified_user_order', to='accounts.User')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_order_product', to='retailer_to_gram.Order')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_ordered_product_received_by_user', to='accounts.User')),
                ('shipped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_shipped_product_ordered_by_user', to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProductMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipped_qty', models.PositiveIntegerField(default=0)),
                ('delivered_qty', models.PositiveIntegerField(default=0)),
                ('returned_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_last_modified_user_order_product', to='accounts.User')),
                ('ordered_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_product_order_product_mapping', to='retailer_to_gram.OrderedProduct')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_product_order_product', to='products.Product')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_note', to='retailer_to_gram.Order'),
        ),
        migrations.AddField(
            model_name='note',
            name='ordered_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtg_order_product_note', to='retailer_to_gram.OrderedProduct'),
        ),
    ]
