# Generated by Django 2.1 on 2018-12-01 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproductmapping',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rt_cart_list', to='retailer_to_gram.Cart'),
        ),
    ]
