# Generated by Django 2.1 on 2018-12-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0003_auto_20181201_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_us', models.URLField(default='info@grmafactory.com')),
                ('contact_us', models.CharField(default='7607846774', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20, null=True)),
                ('select_issue', models.CharField(choices=[('cancellation', ' Cancellation'), ('return', 'Return'), ('others', 'Others')], max_length=100, null=True, verbose_name='Issue')),
                ('complaint_detail', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=4, default='0.0000', max_digits=20)),
                ('payment_choice', models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('neft', 'NEFT')], max_length=30, null=True)),
                ('neft_reference_number', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery'), ('neft', 'NEFT')], max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_payment', to='retailer_to_gram.Order'),
        ),
        migrations.AddField(
            model_name='customercare',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retailer_to_gram.Order'),
        ),
    ]
