# Generated by Django 2.1 on 2018-12-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0003_auto_20181201_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_order_order_product', to='retailer_to_gram.Order'),
        ),
    ]
