# Generated by Django 2.1 on 2018-12-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_to_gram', '0004_auto_20181203_1307'),
        ('retailer_to_gram', '0004_auto_20181212_1212'),
    ]

    operations = [
    ]
