# Generated by Django 2.1 on 2018-09-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerdata',
            old_name='banner',
            new_name='slot',
        ),
        migrations.AlterField(
            model_name='bannerdata',
            name='banner_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_position_data', to='banner.Banner'),
        ),
    ]
