# Generated by Django 2.1 on 2018-09-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20180925_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_below_image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
