# Generated by Django 2.1 on 2018-09-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0003_auto_20180928_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='name',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='banner',
            name='alt_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='text_below_image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
