# Generated by Django 2.1 on 2018-09-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0004_auto_20180928_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
