# Generated by Django 2.1 on 2018-09-28 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_banner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
