# Generated by Django 2.1 on 2018-10-08 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20181008_1319'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTaxMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_tax', to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='country',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='pincode_from',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='pincode_to',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='product',
        ),
        migrations.AddField(
            model_name='productprice',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_pro_price', to='addresses.Area'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_pro_price', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='producttaxmapping',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_pro_tax', to='products.Tax'),
        ),
    ]
