# Generated by Django 2.1 on 2022-04-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
        ('brand', '0002_auto_20220404_1624'),
        ('addresses', '0002_auto_20220404_1624'),
        ('products', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repackaging',
            name='seller_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='repackaging',
            name='source_sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_sku_repackaging', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productvendormapping',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='productvendormapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor_mapping', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productvendormapping',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_vendor_map_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='productvendormapping',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_brand_mapping', to='brand.Vendor'),
        ),
        migrations.AddField(
            model_name='producttaxmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_tax', to='products.Product'),
        ),
        migrations.AddField(
            model_name='producttaxmapping',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_pro_tax', to='products.Tax'),
        ),
        migrations.AddField(
            model_name='productsourcemapping',
            name='destination_sku',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_product_pro', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productsourcemapping',
            name='source_sku',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_product_pro', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Area'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.City'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Country'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.State'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='buyer_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shop_product_price', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_pro_price', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincode_product_price', to='addresses.Pincode'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_price', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='seller_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_price', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='productpackingmapping',
            name='packing_sku',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_material_rt', to='products.Product', verbose_name='Packing Material Sku'),
        ),
        migrations.AddField(
            model_name='productpackingmapping',
            name='sku',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing_product_rt', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_pro_option', to='products.Color'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flavor_pro_option', to='products.Flavor'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='fragrance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fragrance_pro_option', to='products.Fragrance'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='package_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_size_pro_option', to='products.PackageSize'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_opt_product', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size_pro_option', to='products.Size'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_pro_option', to='products.Weight'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_image', to='products.Product'),
        ),
        migrations.AddField(
            model_name='producthsn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='producthsn',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_hsn_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='productcategoryhistory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pro_cat_history', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='productcategoryhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_cat_history', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_pro_category', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_category', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productcapping',
            name='buyer_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_shop_product_capping', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='productcapping',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_pro_capping', to='addresses.City'),
        ),
        migrations.AddField(
            model_name='productcapping',
            name='pincode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pincode_product_capping', to='addresses.Pincode'),
        ),
        migrations.AddField(
            model_name='productcapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_capping', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productcapping',
            name='seller_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_capping', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='productb2ccategoryhistory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_category_pro_b2c_cat_history', to='categories.B2cCategory'),
        ),
        migrations.AddField(
            model_name='productb2ccategoryhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_b2c_cat_history', to='products.Product'),
        ),
        migrations.AddField(
            model_name='productb2ccategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_category_pro_b2c_category', to='categories.B2cCategory'),
        ),
        migrations.AddField(
            model_name='productb2ccategory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_pro_b2c_category', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_sku',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_ref', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_parent_product', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='priceslab',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_slabs', to='products.ProductPrice'),
        ),
        migrations.AddField(
            model_name='parentproducttaxmapping',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_pro_tax', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='parentproducttaxmapping',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tax_pro_tax', to='products.Tax'),
        ),
        migrations.AddField(
            model_name='parentproductimage',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_pro_image', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='parentproductcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category_pro_category', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='parentproductcategory',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_pro_category', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='parentproductb2ccategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category_pro_b2c_category', to='categories.B2cCategory'),
        ),
        migrations.AddField(
            model_name='parentproductb2ccategory',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_pro_b2c_category', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='parent_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_brand_product', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='product_hsn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_hsn', to='products.ProductHSN'),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_product_updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='destinationrepackagingcostmapping',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_product_repackaging', to='products.Product'),
        ),
        migrations.AddField(
            model_name='childproductimage',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_product_pro_image', to='products.Product'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='b2c_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_category_log', to='categories.B2cCategory'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_log', to='brand.Brand'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_log', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='child_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_product_log', to='products.Product'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='hsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hsn_log', to='products.ProductHSN'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='parent_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_log', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='product_vendor_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor_map_log', to='products.ProductVendorMapping'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_log', to='shops.Shop'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='shop_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_type_log', to='shops.ShopType'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='shop_user_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_user_map_log', to='shops.ShopUserMapping'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_log', to='products.Tax'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='centrallog',
            name='weight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_log', to='products.Weight'),
        ),
        migrations.AddField(
            model_name='bulkuploadforproductattributes',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulk_file_uploaded_by', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='bulkuploadforgstchange',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulk_product_gst_update', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='bulkproducttaxupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bulk_product_tax_update', to='accounts.User'),
        ),
        migrations.CreateModel(
            name='DiscountedProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='DiscountedProductPrice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('products.productprice',),
        ),
        migrations.CreateModel(
            name='SlabProductPrice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('products.productprice',),
        ),
        migrations.AlterUniqueTogether(
            name='productpackingmapping',
            unique_together={('sku', 'packing_sku')},
        ),
    ]
