# Generated by Django 2.1 on 2018-10-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_to_retailer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_to_service_partner',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productprice',
            name='price_to_super_retailer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
