# Generated by Django 2.1 on 2022-04-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_auto_20220406_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTaxMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_group', to='products.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='ParentProductTaxApprovalLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('tax_status', models.CharField(blank=True, max_length=10, null=True)),
                ('tax_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHsnCess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('cess', models.IntegerField(choices=[(0, 'CESS-0'), (5, 'CESS-5'), (12, 'CESS-12'), (36, 'CESS-36')], null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
                ('product_hsn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hsn_cess', to='products.ProductHSN')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHsnGst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('gst', models.IntegerField(choices=[(0, 'GST-0'), (5, 'GST-5'), (12, 'GST-12'), (18, 'GST-18'), (28, 'GST-28')], null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
                ('product_hsn', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hsn_gst', to='products.ProductHSN')),
            ],
        ),
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('zoho_id', models.CharField(max_length=100)),
                ('is_igst', models.BooleanField(default=False)),
                ('zoho_grp_type', models.CharField(choices=[('TAX_GROUP', 'Tax Group'), ('TAX_SINGLE', 'itemAmount')], max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.User', verbose_name='Created by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='parentproduct',
            options={'ordering': ['-created_at'], 'permissions': (('can_approve_product_tax', 'Can Approve Product TAX.'),)},
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='tax_remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentproduct',
            name='tax_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending For Approval'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='parentproducttaxapprovallog',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_product_tax_approval_log', to='products.ParentProduct'),
        ),
        migrations.AddField(
            model_name='grouptaxmapping',
            name='tax_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_taxes', to='products.TaxGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='producthsngst',
            unique_together={('product_hsn', 'gst')},
        ),
        migrations.AlterUniqueTogether(
            name='producthsncess',
            unique_together={('product_hsn', 'cess')},
        ),
        migrations.AlterUniqueTogether(
            name='grouptaxmapping',
            unique_together={('tax_group', 'tax')},
        ),
    ]
