# Generated by Django 2.1 on 2018-10-16 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20181010_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_PRODUCT_NAME', message='Invalid product name. Special characters allowed are _ , @ . / # & + -', regex='^[ \\w\\$\\_\\,\\@\\.\\/\\#\\&\\+\\-\\(\\)]*$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_short_description',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_PRODUCT_NAME', message='Invalid product name. Special characters allowed are _ , @ . / # & + -', regex='^[ \\w\\$\\_\\,\\@\\.\\/\\#\\&\\+\\-\\(\\)]*$')]),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_PRODUCT_NAME', message='Invalid product name. Special characters allowed are _ , @ . / # & + -', regex='^[ \\w\\$\\_\\,\\@\\.\\/\\#\\&\\+\\-\\(\\)]*$')]),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product_short_description',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_PRODUCT_NAME', message='Invalid product name. Special characters allowed are _ , @ . / # & + -', regex='^[ \\w\\$\\_\\,\\@\\.\\/\\#\\&\\+\\-\\(\\)]*$')]),
        ),
    ]
