# Generated by Django 2.1 on 2018-10-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181016_1227'),
        ('products', '0004_auto_20181016_1505'),
    ]

    operations = [
    ]
