# Generated by Django 2.1 on 2018-10-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20181010_1702'),
        ('products', '0006_productpricecsv'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricecsv',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.City'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Country'),
        ),
        migrations.AddField(
            model_name='productpricecsv',
            name='states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.State'),
        ),
    ]
