# Generated by Django 2.1 on 2022-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_parentproduct_tax_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentproduct',
            name='tax_remark',
        ),
    ]
