# Generated by Django 2.1 on 2022-04-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_parentproduct_tax_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='tax_remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
