# Generated by Django 2.1 on 2018-10-17 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20181008_1319'),
        ('products', '0007_auto_20181016_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='shop_type',
        ),
        migrations.AddField(
            model_name='productprice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_product_price', to='shops.Shop'),
        ),
    ]
