# Generated by Django 2.1 on 2018-10-17 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20181010_1702'),
        ('products', '0008_auto_20181017_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricecsv',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.Area'),
        ),
    ]
