# Generated by Django 2.1 on 2018-11-10 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productpricecsv_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesize',
            name='pack_height',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='packagesize',
            name='pack_length',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='packagesize',
            name='pack_size_unit',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='packagesize',
            name='pack_width',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='size',
            name='size_unit',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight_unit',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
    ]
