# Generated by Django 2.1 on 2018-11-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_auto_20181128_1807'),
        ('products', '0010_auto_20181110_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVendorMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_vendor_mapping', to='products.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_brand_mapping', to='brand.Vendor')),
            ],
        ),
    ]
