# Generated by Django 2.2 on 2022-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0020_auto_20220617_1613'),
        ('products', '0010_auto_20220617_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperStoreProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='super_store_created_by', to='accounts.User', verbose_name='Created by')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_store_product_price', to='products.Product')),
                ('seller_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_store_product_price', to='shops.Shop')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='super_store_updated_by', to='accounts.User', verbose_name='Updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='parentproduct',
            name='product_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('superstore', 'SuperStore')], default='grocery', max_length=10),
        ),
        migrations.AlterField(
            model_name='parentproducttaxapprovallog',
            name='parent_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_product_tax_approval_log', to='products.ParentProduct'),
        ),
        migrations.CreateModel(
            name='SuperStoreProductPriceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_selling_price', models.FloatField(blank=True, null=True)),
                ('new_selling_price', models.FloatField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('product_price_change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_price_change_log', to='products.SuperStoreProductPrice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='super_store_price_changed_by', to='accounts.User')),
            ],
        ),
    ]
