# Generated by Django 2.1 on 2018-11-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productvendormapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendormapping',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='Brand To Gram Price'),
        ),
    ]
