# Generated by Django 2.2 on 2022-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20220617_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentproduct',
            name='is_kvi',
            field=models.BooleanField(default=False),
        ),
    ]
