# Generated by Django 2.1 on 2018-11-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181129_1200'),
        ('products', '0012_auto_20181129_1139'),
    ]

    operations = [
    ]
