# Generated by Django 2.1 on 2018-11-29 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181129_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagesize',
            name='pack_size_unit',
            field=models.CharField(choices=[('mm', 'Millimeter'), ('cm', 'Centimeter'), ('dm', 'Decimeter'), ('m', 'Meter')], default='mm', max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
    ]
