# Generated by Django 2.1 on 2018-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181129_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=models.SlugField(unique=True),
        ),
    ]
