# Generated by Django 2.1 on 2018-11-29 15:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181129_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size_name',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='size_value'),
        ),
    ]
