# Generated by Django 2.1 on 2018-11-29 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20181129_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight_name',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('mg', 'Milligram')], default='kg', max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_UNIT_NAME', message='Invalid unit name (eg: kg, litres)', regex='^[a-zA-Z]+$')]),
        ),
    ]
