# Generated by Django 2.1 on 2018-11-29 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20181129_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='tax_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_PRODUCT_NAME', message='Invalid product name. Special characters allowed are _ , @ . / # & + -', regex='^[ \\w\\$\\_\\,\\@\\.\\/\\#\\&\\+\\-\\(\\)]*$')]),
        ),
    ]
