# Generated by Django 2.1 on 2018-11-29 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20181129_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ean_code',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='INVALID_EAN_CODE', message='Invalid EAN code. Exactly 13 numbers required', regex='^\\d{13}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sku',
            field=models.CharField(max_length=255),
        ),
    ]
