# Generated by Django 2.1 on 2018-12-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20181129_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_inner_case_size',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
