# Generated by Django 2.1 on 2018-12-10 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_productskugenerator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productskugenerator',
            name='brand_sku_code',
            field=models.CharField(help_text='Please enter three characters for SKU', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')]),
        ),
        migrations.AlterField(
            model_name='productskugenerator',
            name='cat_sku_code',
            field=models.CharField(help_text='Please enter three characters for SKU', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')]),
        ),
        migrations.AlterField(
            model_name='productskugenerator',
            name='parent_cat_sku_code',
            field=models.CharField(help_text='Please enter three characters for SKU', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Only three capital alphates allowed')]),
        ),
    ]
