# Generated by Django 2.1 on 2018-12-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_auto_20181210_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productskugenerator',
            name='last_auto_increment',
            field=models.CharField(max_length=8),
        ),
    ]
