# Generated by Django 2.1 on 2018-12-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20181217_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_case_size',
            field=models.CharField(max_length=255),
        ),
    ]
