# Generated by Django 2.1 on 2018-12-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20181217_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvendormapping',
            name='product_price',
            field=models.FloatField(verbose_name='Brand To Gram Price'),
        ),
    ]
